from PyQt5.QtCore import pyqtSignal
from PyQt5.QtWidgets import QMainWindow, QWidget, QPushButton, QApplication, QVBoxLayout
from PyQt5 import QtCore, QtGui, QtWidgets

from src.backend.connection import get_min_consumption, get_max_consumption, get_avrg_consumption, \
    get_current_month_consumption
from src.backend.dictionaries import oids, source_dic
from src.backend.snmp_protocole import snmp_get



class ConsumptionView(QWidget):

    switch_to_dashboard_page = pyqtSignal()
    switch_to_statistics_page = pyqtSignal()
    switch_to_onduleurs_page = pyqtSignal()
    switch_to_home_page = pyqtSignal()
    switch_to_documentation_page = pyqtSignal()

    def __init__(self):
        super().__init__()
        self.setStyleSheet("background-color: rgb(41, 45, 57);")
        self.setObjectName("Consomation")
        self.layout = QVBoxLayout()
        self.centralwidget = QtWidgets.QWidget()
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame.setStyleSheet("background-color: rgb(41, 45, 57);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setMinimumSize(QtCore.QSize(110, 0))
        self.frame_5.setMaximumSize(QtCore.QSize(110, 100))
        self.frame_5.setStyleSheet("background-color: rgb(32, 136, 245);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_5)
        self.refresh_button = QPushButton(self.frame_5)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./src/icons/refresh-icon.png"), QtGui.QIcon.Normal,
                       QtGui.QIcon.Off)
        self.refresh_button.setIcon(icon)
        self.refresh_button.setIconSize(QtCore.QSize(100, 100))
        self.refresh_button.setFlat(True)
        self.refresh_button.setObjectName("refresh_button")
        self.gridLayout.addWidget(self.refresh_button, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.documentation_button = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.documentation_button.setFont(font)
        self.documentation_button.setStyleSheet("QPushButton{\n"
                                                "    color: rgb(255, 255, 255);}")
        self.documentation_button.setFlat(True)
        self.documentation_button.setObjectName("notifications_button")
        self.horizontalLayout_2.addWidget(self.documentation_button)
        self.titile_label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.titile_label.setFont(font)
        self.titile_label.setStyleSheet("QLabel{\n"
                                        "    color: rgb(255, 255, 255);}")
        self.titile_label.setAlignment(QtCore.Qt.AlignCenter)
        self.titile_label.setObjectName("titile_label")
        self.horizontalLayout_2.addWidget(self.titile_label)
        self.logout_button = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.logout_button.setFont(font)
        self.logout_button.setStyleSheet("QPushButton{\n"
                                         "    color: rgb(255, 255, 255);}")
        self.logout_button.setFlat(True)
        self.logout_button.setObjectName("logout_button")
        self.horizontalLayout_2.addWidget(self.logout_button)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMinimumSize(QtCore.QSize(110, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(110, 16777215))
        self.frame_3.setStyleSheet("background-color: rgb(41, 45, 57);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_13 = QtWidgets.QFrame(self.frame_3)
        self.frame_13.setMaximumSize(QtCore.QSize(16777215, 130))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.dashboard_icon_button = QtWidgets.QPushButton(self.frame_13)
        self.dashboard_icon_button.setMaximumSize(QtCore.QSize(167777, 167777))
        self.dashboard_icon_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./src/icons/dashbord.png"), QtGui.QIcon.Normal,
                       QtGui.QIcon.Off)
        self.dashboard_icon_button.setIcon(icon)
        self.dashboard_icon_button.setIconSize(QtCore.QSize(70, 70))
        self.dashboard_icon_button.setFlat(True)
        self.dashboard_icon_button.setObjectName("dashboard_icon_button")
        self.verticalLayout_10.addWidget(self.dashboard_icon_button)
        self.dashborad_button = QtWidgets.QPushButton(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.dashborad_button.setFont(font)
        self.dashborad_button.setStyleSheet("QPushButton{\n"
                                             "    color: rgb(255, 255, 255);}")
        self.dashborad_button.setFlat(True)
        self.dashborad_button.setObjectName("dashborad1_button")
        self.verticalLayout_10.addWidget(self.dashborad_button)
        self.verticalLayout_9.addWidget(self.frame_13)
        self.frame_14 = QtWidgets.QFrame(self.frame_3)
        self.frame_14.setMaximumSize(QtCore.QSize(16777215, 130))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.statistiques_icon_button = QtWidgets.QPushButton(self.frame_14)
        self.statistiques_icon_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./src/icons/statistic-icon.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.statistiques_icon_button.setIcon(icon1)
        self.statistiques_icon_button.setIconSize(QtCore.QSize(70, 70))
        self.statistiques_icon_button.setFlat(True)
        self.statistiques_icon_button.setObjectName("consomation_icon_button")
        self.verticalLayout_11.addWidget(self.statistiques_icon_button)
        self.statistiques_button = QtWidgets.QPushButton(self.frame_14)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.statistiques_button.setFont(font)
        self.statistiques_button.setStyleSheet("QPushButton{\n"
                                              "    color: rgb(255, 255, 255);}")
        self.statistiques_button.setFlat(True)
        self.statistiques_button.setObjectName("consomation_button")
        self.verticalLayout_11.addWidget(self.statistiques_button)
        self.verticalLayout_9.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(self.frame_3)
        self.frame_15.setMaximumSize(QtCore.QSize(16777215, 130))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.onduleur_icon_button = QtWidgets.QPushButton(self.frame_15)
        self.onduleur_icon_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./src/icons/onduleur-icon1.jpg"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.onduleur_icon_button.setIcon(icon2)
        self.onduleur_icon_button.setIconSize(QtCore.QSize(70, 70))
        self.onduleur_icon_button.setFlat(True)
        self.onduleur_icon_button.setObjectName("onduleur_icon_button")
        self.verticalLayout_12.addWidget(self.onduleur_icon_button)
        self.onduleur_button = QtWidgets.QPushButton(self.frame_15)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.onduleur_button.setFont(font)
        self.onduleur_button.setStyleSheet("QPushButton{\n"
                                           "    color: rgb(255, 255, 255);}")
        self.onduleur_button.setFlat(True)
        self.onduleur_button.setObjectName("onduleur_button")
        self.verticalLayout_12.addWidget(self.onduleur_button)
        self.verticalLayout_9.addWidget(self.frame_15)
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setStyleSheet("background-color: rgb(53, 58, 69);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.consomation_frame = QtWidgets.QFrame(self.frame_4)
        self.consomation_frame.setStyleSheet("QFrame{\n"
                                             "    background-color: rgb(41, 45, 57);\n"
                                             "    border-radius:15px;\n"
                                             "}")
        self.consomation_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.consomation_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.consomation_frame.setObjectName("consomation_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.consomation_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.consomation_frame)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.title_label = QtWidgets.QLabel(self.frame_6)
        self.title_label.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet("QLabel{\n"
                                       "    color: rgb(255, 255, 255);}")
        self.title_label.setObjectName("title_label")
        self.verticalLayout_4.addWidget(self.title_label)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.frame_8 = QtWidgets.QFrame(self.consomation_frame)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.value_label = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(100)
        font.setBold(True)
        font.setWeight(75)
        self.value_label.setFont(font)
        self.value_label.setStyleSheet("QLabel{\n"
                                       "    color: rgb(255, 255, 255);}")
        self.value_label.setAlignment(QtCore.Qt.AlignCenter)
        self.value_label.setObjectName("value_label")
        self.verticalLayout_6.addWidget(self.value_label)
        self.verticalLayout_5.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.frame_8)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_11 = QtWidgets.QFrame(self.frame_10)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.max_label = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.max_label.setFont(font)
        self.max_label.setStyleSheet("QLabel{\n"
                                     "    color: rgb(255, 255, 255);}")
        self.max_label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.max_label.setObjectName("max_label")
        self.verticalLayout_7.addWidget(self.max_label)


        self.moyenne_label = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.moyenne_label.setFont(font)
        self.moyenne_label.setStyleSheet("QLabel{\n"
                                         "    color: rgb(255, 255, 255);}")
        self.moyenne_label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.moyenne_label.setObjectName("moyenne_label")
        self.verticalLayout_7.addWidget(self.moyenne_label)
        self.mini_label = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.mini_label.setFont(font)
        self.mini_label.setStyleSheet("QLabel{\n"
                                      "    color: rgb(255, 255, 255);}")
        self.mini_label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.mini_label.setObjectName("mini_label")
        self.verticalLayout_7.addWidget(self.mini_label)
        self.horizontalLayout_5.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.frame_10)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_8.setContentsMargins(11, -1, 11, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.max_value_label = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.max_value_label.setFont(font)
        self.max_value_label.setStyleSheet("QLabel{\n"
                                           "    color: rgb(255, 255, 255);}")
        self.max_value_label.setObjectName("max_value_label")
        self.verticalLayout_8.addWidget(self.max_value_label)
        self.average_label = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.average_label.setFont(font)
        self.average_label.setStyleSheet("QLabel{\n"
                                         "    color: rgb(255, 255, 255);}")
        self.average_label.setObjectName("average_label")
        self.verticalLayout_8.addWidget(self.average_label)
        self.min_value_label = QtWidgets.QLabel(self.frame_12)
        self.min_value_label.setStyleSheet("QLabel{\n"
                                                   "    color: rgb(255, 255, 255);}")
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.min_value_label.setFont(font)

        self.horizontalLayout_5.addWidget(self.frame_12)
        self.verticalLayout_5.addWidget(self.frame_10)
        self.verticalLayout_3.addWidget(self.frame_8)
        self.horizontalLayout_3.addWidget(self.consomation_frame)
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.source_frame = QtWidgets.QFrame(self.frame_7)
        self.source_frame.setStyleSheet("QFrame{\n"
                                        "    background-color: rgb(41, 45, 57);\n"
                                        "border-radius:15px;}")
        self.source_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.source_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.source_frame.setObjectName("source_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.source_frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.source_label = QtWidgets.QLabel(self.source_frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.source_label.setFont(font)
        self.source_label.setStyleSheet("QLabel{\n"
                                        "    color: rgb(255, 255, 255);}")
        self.source_label.setObjectName("source_label")
        self.horizontalLayout_4.addWidget(self.source_label)
        self.source_type_label = QtWidgets.QLabel(self.source_frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.source_type_label.setFont(font)
        self.source_type_label.setStyleSheet("QLabel{\n"
                                             "    color: rgb(255, 255, 255);}")
        self.source_type_label.setObjectName("source_type_label")
        self.horizontalLayout_4.addWidget(self.source_type_label)
        self.verticalLayout_2.addWidget(self.source_frame)

        self.class_energie_frame = QtWidgets.QFrame(self.frame_7)
        self.class_energie_frame.setMinimumSize(QtCore.QSize(0, 830))
        self.class_energie_frame.setStyleSheet("QFrame{\n"
                                               "    background-color: rgb(41, 45, 57);\n"
                                               "border-radius:15px;}")
        self.class_energie_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.class_energie_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.class_energie_frame.setObjectName("class_energie_frame")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.class_energie_frame)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_16 = QtWidgets.QFrame(self.class_energie_frame)
        self.frame_16.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.class_title_frame = QtWidgets.QLabel(self.frame_16)
        self.class_title_frame.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.class_title_frame.setFont(font)
        self.class_title_frame.setStyleSheet("QLabel{\n"
                                             "    color: rgb(255, 255, 255);}")
        self.class_title_frame.setObjectName("class_title_frame")
        self.verticalLayout_14.addWidget(self.class_title_frame)
        self.verticalLayout_13.addWidget(self.frame_16)
        self.frame_17 = QtWidgets.QFrame(self.class_energie_frame)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_18 = QtWidgets.QFrame(self.frame_17)
        self.frame_18.setMinimumSize(QtCore.QSize(650, 0))
        self.frame_18.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(30)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_20 = QtWidgets.QFrame(self.frame_18)
        self.frame_20.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.class_a_widget = QtWidgets.QWidget(self.frame_20)
        self.class_a_widget.setStyleSheet("QWidget{\n"
                                          "    background-color: #01A552;\n"
                                          "    border-radius:15px;\n"
                                          "}")
        self.class_a_widget.setObjectName("class_a_widget")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.class_a_widget)
        self.horizontalLayout_18.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_13 = QtWidgets.QLabel(self.class_a_widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_18.addWidget(self.label_13)
        self.label_25 = QtWidgets.QLabel(self.class_a_widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_18.addWidget(self.label_25)
        self.label_46 = QtWidgets.QLabel(self.class_a_widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_46.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_18.addWidget(self.label_46)
        self.horizontalLayout_13.addWidget(self.class_a_widget)
        self.verticalLayout_15.addWidget(self.frame_20)
        self.frame_21 = QtWidgets.QFrame(self.frame_18)
        self.frame_21.setMaximumSize(QtCore.QSize(316, 16777215))
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.class_b_widget = QtWidgets.QWidget(self.frame_21)
        self.class_b_widget.setStyleSheet("QWidget{\n"
                                          "    background-color: #4DB749;\n"
                                          "    border-radius:15px;\n"
                                          "}")
        self.class_b_widget.setObjectName("class_b_widget")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.class_b_widget)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_42 = QtWidgets.QLabel(self.class_b_widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_20.addWidget(self.label_42)
        self.label_24 = QtWidgets.QLabel(self.class_b_widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_20.addWidget(self.label_24)
        self.label_47 = QtWidgets.QLabel(self.class_b_widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_47.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_20.addWidget(self.label_47)
        self.horizontalLayout_12.addWidget(self.class_b_widget)
        self.verticalLayout_15.addWidget(self.frame_21)
        self.frame_22 = QtWidgets.QFrame(self.frame_18)
        self.frame_22.setMaximumSize(QtCore.QSize(382, 16777215))
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.class_c_widget = QtWidgets.QWidget(self.frame_22)
        self.class_c_widget.setStyleSheet("QWidget{\n"
                                          "    background-color: #86962E;\n"
                                          "    border-radius:15px;\n"
                                          "}")
        self.class_c_widget.setObjectName("class_c_widget")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.class_c_widget)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_51 = QtWidgets.QLabel(self.class_c_widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_51.setFont(font)
        self.label_51.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_19.addWidget(self.label_51)
        self.label_23 = QtWidgets.QLabel(self.class_c_widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_19.addWidget(self.label_23)
        self.label_49 = QtWidgets.QLabel(self.class_c_widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_49.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_19.addWidget(self.label_49)
        self.horizontalLayout_11.addWidget(self.class_c_widget)
        self.verticalLayout_15.addWidget(self.frame_22)
        self.frame_23 = QtWidgets.QFrame(self.frame_18)
        self.frame_23.setMaximumSize(QtCore.QSize(448, 16777215))
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.class_d_widget = QtWidgets.QWidget(self.frame_23)
        self.class_d_widget.setStyleSheet("QWidget{\n"
                                          "    background-color: #FFF001;\n"
                                          "    border-radius:15px;\n"
                                          "}")
        self.class_d_widget.setObjectName("class_d_widget")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.class_d_widget)
        self.horizontalLayout_17.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_37 = QtWidgets.QLabel(self.class_d_widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_17.addWidget(self.label_37)
        self.label_22 = QtWidgets.QLabel(self.class_d_widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_17.addWidget(self.label_22)
        self.label_50 = QtWidgets.QLabel(self.class_d_widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_50.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_17.addWidget(self.label_50)
        self.horizontalLayout_10.addWidget(self.class_d_widget)
        self.verticalLayout_15.addWidget(self.frame_23)
        self.frame_24 = QtWidgets.QFrame(self.frame_18)
        self.frame_24.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_24.setMaximumSize(QtCore.QSize(514, 16777215))
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_24)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.class_e_widget = QtWidgets.QWidget(self.frame_24)
        self.class_e_widget.setStyleSheet("QWidget{\n"
                                          "    background-color: #FDB813;\n"
                                          "    border-radius:15px;\n"
                                          "}")
        self.class_e_widget.setObjectName("class_e_widget")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.class_e_widget)
        self.horizontalLayout_16.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_48 = QtWidgets.QLabel(self.class_e_widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_16.addWidget(self.label_48)
        self.label_21 = QtWidgets.QLabel(self.class_e_widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_16.addWidget(self.label_21)
        self.label_52 = QtWidgets.QLabel(self.class_e_widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_52.setFont(font)
        self.label_52.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_52.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_16.addWidget(self.label_52)
        self.horizontalLayout_9.addWidget(self.class_e_widget)
        self.verticalLayout_15.addWidget(self.frame_24)
        self.frame_26 = QtWidgets.QFrame(self.frame_18)
        self.frame_26.setMaximumSize(QtCore.QSize(580, 16777215))
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_26)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.class_f_widget = QtWidgets.QWidget(self.frame_26)
        self.class_f_widget.setMaximumSize(QtCore.QSize(700, 16777215))
        self.class_f_widget.setStyleSheet("QWidget{\n"
                                          "    background-color: #F37022;\n"
                                          "    border-radius:15px;\n"
                                          "}")
        self.class_f_widget.setObjectName("class_f_widget")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.class_f_widget)
        self.horizontalLayout_15.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_20 = QtWidgets.QLabel(self.class_f_widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_15.addWidget(self.label_20)
        self.label_19 = QtWidgets.QLabel(self.class_f_widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_15.addWidget(self.label_19)
        self.label_53 = QtWidgets.QLabel(self.class_f_widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_53.setFont(font)
        self.label_53.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_53.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_15.addWidget(self.label_53)
        self.horizontalLayout_8.addWidget(self.class_f_widget)
        self.verticalLayout_15.addWidget(self.frame_26)
        self.frame_red = QtWidgets.QFrame(self.frame_18)
        self.frame_red.setMaximumSize(QtCore.QSize(646, 16777215))
        self.frame_red.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_red.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_red.setObjectName("frame_red")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_red)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.class_g_widget = QtWidgets.QWidget(self.frame_red)
        self.class_g_widget.setMaximumSize(QtCore.QSize(650, 16777215))
        self.class_g_widget.setStyleSheet("QWidget{\n"
                                          "    background-color: rgb(237, 27, 36);\n"
                                          "    border-radius:15px;\n"
                                          "}")
        self.class_g_widget.setObjectName("class_g_widget")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.class_g_widget)
        self.horizontalLayout_14.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_17 = QtWidgets.QLabel(self.class_g_widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_14.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.class_g_widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_14.addWidget(self.label_18)
        self.label_54 = QtWidgets.QLabel(self.class_g_widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_54.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_14.addWidget(self.label_54)
        self.horizontalLayout_7.addWidget(self.class_g_widget)
        self.verticalLayout_15.addWidget(self.frame_red)
        self.horizontalLayout_6.addWidget(self.frame_18)
        self.frame_19 = QtWidgets.QFrame(self.frame_17)
        self.frame_19.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.frame_27 = QtWidgets.QFrame(self.frame_19)
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_27)
        self.verticalLayout_16.setContentsMargins(11, 11, 0, -1)
        self.verticalLayout_16.setSpacing(70)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame_33 = QtWidgets.QFrame(self.frame_27)
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.frame_33)
        self.horizontalLayout_25.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.bar_7 = QtWidgets.QWidget(self.frame_33)

        self.bar_7.setObjectName("bar_7")
        self.horizontalLayout_25.addWidget(self.bar_7)
        self.verticalLayout_16.addWidget(self.frame_33)
        self.frame_32 = QtWidgets.QFrame(self.frame_27)
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.frame_32)
        self.horizontalLayout_24.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.bar_6 = QtWidgets.QWidget(self.frame_32)

        self.bar_6.setObjectName("bar_6")
        self.horizontalLayout_24.addWidget(self.bar_6)
        self.verticalLayout_16.addWidget(self.frame_32)
        self.frame_34 = QtWidgets.QFrame(self.frame_27)
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_34)
        self.horizontalLayout_23.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.bar = QtWidgets.QWidget(self.frame_34)

        self.bar.setObjectName("bar")
        self.horizontalLayout_23.addWidget(self.bar)
        self.verticalLayout_16.addWidget(self.frame_34)
        self.frame_31 = QtWidgets.QFrame(self.frame_27)
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_31)
        self.verticalLayout_20.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.bar_5 = QtWidgets.QWidget(self.frame_31)

        self.bar_5.setObjectName("bar_5")
        self.verticalLayout_20.addWidget(self.bar_5)
        self.verticalLayout_16.addWidget(self.frame_31)
        self.frame_30 = QtWidgets.QFrame(self.frame_27)
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_30)
        self.verticalLayout_19.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.bar_4 = QtWidgets.QWidget(self.frame_30)

        self.bar_4.setObjectName("bar_4")
        self.verticalLayout_19.addWidget(self.bar_4)
        self.verticalLayout_16.addWidget(self.frame_30)
        self.frame_29 = QtWidgets.QFrame(self.frame_27)
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_29)
        self.verticalLayout_18.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.bar_3 = QtWidgets.QWidget(self.frame_29)

        self.bar_3.setObjectName("bar_3")
        self.verticalLayout_18.addWidget(self.bar_3)
        self.verticalLayout_16.addWidget(self.frame_29)
        self.frame_28 = QtWidgets.QFrame(self.frame_27)
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_28)
        self.verticalLayout_17.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.bar_2 = QtWidgets.QWidget(self.frame_28)

        self.bar_2.setObjectName("bar_2")
        self.verticalLayout_17.addWidget(self.bar_2)
        self.verticalLayout_16.addWidget(self.frame_28)
        self.horizontalLayout_21.addWidget(self.frame_27)
        self.frame_25 = QtWidgets.QFrame(self.frame_19)
        self.frame_25.setMaximumSize(QtCore.QSize(10, 16777215))
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame_25)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setSpacing(0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.bar2 = QtWidgets.QWidget(self.frame_25)
        self.bar2.setMaximumSize(QtCore.QSize(10, 16777215))
        self.bar2.setStyleSheet("QWidget{\n"
                                "    background-color: rgb(140, 153, 179);}")
        self.bar2.setObjectName("bar2")
        self.horizontalLayout_22.addWidget(self.bar2)
        self.horizontalLayout_21.addWidget(self.frame_25)
        self.horizontalLayout_6.addWidget(self.frame_19)
        self.verticalLayout_13.addWidget(self.frame_17)
        self.verticalLayout_2.addWidget(self.class_energie_frame)
        self.horizontalLayout_3.addWidget(self.frame_7)
        self.horizontalLayout.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame_2)

        self.total_consumption_label = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.total_consumption_label.setFont(font)
        self.total_consumption_label.setStyleSheet("QLabel{\n"
                                                   "    color: rgb(255, 255, 255);}")
        self.total_consumption_label.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.total_consumption_label.setObjectName("total_consumption_label")
        self.total_consumption_label.setStyleSheet("QLabel{\n"
                                                   "    color: rgb(255, 255, 255);}")
        self.total_consumption_label.setText("Consomation totale :")
        self.verticalLayout_7.addWidget(self.total_consumption_label)
        self.total_cosumption_value = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.total_cosumption_value.setFont(font)
        self.total_cosumption_value.setStyleSheet("QLabel{\n"
                                                  "    color: rgb(255, 255, 255);}")
        self.total_cosumption_value.setObjectName("min_value_label")
        self.verticalLayout_8.addWidget(self.min_value_label)
        self.verticalLayout_8.addWidget(self.total_cosumption_value)

        self.logout_button.clicked.connect(self.switch_to_home_page.emit)
        self.documentation_button.clicked.connect(self.switch_to_documentation_page.emit)
        self.onduleur_button.clicked.connect(self.switch_to_onduleurs_page.emit)
        self.onduleur_icon_button.clicked.connect(self.switch_to_onduleurs_page.emit)
        self.dashborad_button.clicked.connect(self.switch_to_dashboard_page.emit)
        self.dashboard_icon_button.clicked.connect(self.switch_to_dashboard_page.emit)
        self.statistiques_icon_button.clicked.connect(self.switch_to_dashboard_page.emit)
        self.statistiques_button.clicked.connect(self.switch_to_dashboard_page.emit)
        self.refresh_button.clicked.connect(self.refresh_page)

        self.updateLabels()
        self.retranslateUi(self)

        self.layout.addWidget(self.centralwidget)
        self.layout.setContentsMargins(0, 0, 0, 0)
        self.setLayout(self.layout)

    totale_consumption = round(get_current_month_consumption(), 2)

    def updateLabels(self):
        try:
            consumption = round(float(snmp_get(oids.get("outputWatt"), '192.168.12.113')), 2)
            source = snmp_get(oids.get("source"), '192.168.12.113')
            self.min_value_label.setText("%s W/h" % str(round(get_min_consumption(), 2)))
            self.max_value_label.setText("%s W/h" % str(round(get_max_consumption(), 2)))
            self.average_label.setText("%s W/h" % str(round(get_avrg_consumption(), 2)))
            self.source_type_label.setText(source_dic.get(source))
            self.value_label.setText("%s W/h" % str(consumption))
            self.total_cosumption_value.setText("%s W" % str(self.totale_consumption))

            self.min_value_label.adjustSize()
            self.average_label.adjustSize()
            self.source_type_label.adjustSize()
            self.value_label.adjustSize()

            self.define_bars_color()

        except:
            raise ValueError("Verifiez la connexion avec les onduleurs")




    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.documentation_button.setText(_translate("MainWindow", "Documentation"))
        self.titile_label.setText(_translate("MainWindow", "Consomation"))
        self.logout_button.setText(_translate("MainWindow", "Deconnecter"))
        self.dashborad_button.setText(_translate("MainWindow", "Tableau de\n"
"board"))
        self.statistiques_button.setText(_translate("MainWindow", "Statistiques"))
        self.onduleur_button.setText(_translate("MainWindow", "Onduleurs"))
        self.title_label.setText(_translate("MainWindow", "Consomation :"))
        self.max_label.setText(_translate("MainWindow", "Maximume :"))
        self.moyenne_label.setText(_translate("MainWindow", "Moyenne    :"))
        self.mini_label.setText(_translate("MainWindow", "Minimume  :"))
        self.source_label.setText(_translate("MainWindow", "Source :"))
        self.class_title_frame.setText(_translate("MainWindow", "Classe d\'energie :"))
        self.label_13.setText(_translate("MainWindow", "<"))
        self.label_25.setText(_translate("MainWindow", "100"))
        self.label_46.setText(_translate("MainWindow", "A"))
        self.label_42.setText(_translate("MainWindow", "<"))
        self.label_24.setText(_translate("MainWindow", "200"))
        self.label_47.setText(_translate("MainWindow", "B"))
        self.label_51.setText(_translate("MainWindow", "<"))
        self.label_23.setText(_translate("MainWindow", "300"))
        self.label_49.setText(_translate("MainWindow", "C"))
        self.label_37.setText(_translate("MainWindow", "<"))
        self.label_22.setText(_translate("MainWindow", "400"))
        self.label_50.setText(_translate("MainWindow", "D"))
        self.label_48.setText(_translate("MainWindow", "<"))
        self.label_21.setText(_translate("MainWindow", "500"))
        self.label_52.setText(_translate("MainWindow", "E"))
        self.label_20.setText(_translate("MainWindow", "<"))
        self.label_19.setText(_translate("MainWindow", "600"))
        self.label_53.setText(_translate("MainWindow", "F"))
        self.label_17.setText(_translate("MainWindow", ">"))
        self.label_18.setText(_translate("MainWindow", "700"))
        self.label_54.setText(_translate("MainWindow", "G"))

    def empty_labels(self):
        self.min_value_label.setText(None)
        self.average_label.setText(None)
        self.source_type_label.setText(None)
        self.value_label.setText(None)


    def refresh_page(self):
        self.empty_labels()
        self.updateLabels()

    def define_bars_color(self):
        self.bar_2.setStyleSheet("QWidget{\n"
                                 "    border-radius:20px;\n"
                                 "    background-color: rgb(41, 45, 57);\n"
                                 "}")
        self.bar_3.setStyleSheet("QWidget{\n"
                                 "    border-radius:20px;\n"
                                 "    background-color: rgb(41, 45, 57);\n"
                                 "}")
        self.bar_4.setStyleSheet("QWidget{\n"
                                 "    border-radius:20px;\n"
                                 "    background-color: rgb(41, 45, 57);\n"
                                 "}")
        self.bar_5.setStyleSheet("QWidget{\n"
                                 "    border-radius:20px;\n"
                                 "    background-color: rgb(41, 45, 57);\n"
                                 "}")
        self.bar_6.setStyleSheet("QWidget{\n"
                                 "    border-radius:20px;\n"
                                 "    background-color: rgb(41, 45, 57);\n"
                                 "}")
        self.bar_7.setStyleSheet("QWidget{\n"
                                 "    border-radius:20px;\n"
                                 "    background-color: rgb(41, 45, 57);\n"
                                 "}")
        self.bar.setStyleSheet("QWidget{\n"
                               "    border-radius:20px;\n"
                               "    background-color: rgb(41, 45, 57);\n"
                               "}")
        self.update_bars_color()

    def update_bars_color(self):
        if self.totale_consumption <= 100:
            self.bar_7.setStyleSheet("QWidget{\n"
                                     "    border-radius:20px;\n"
                                     "    background-color: rgb(140, 153, 179);;\n"
                                     "}")

        elif self.totale_consumption <= 200:
            self.bar_6.setStyleSheet("QWidget{\n"
                                     "    border-radius:20px;\n"
                                     "    background-color: rgb(140, 153, 179);;\n"
                                     "}")

        elif self.totale_consumption <= 300:
            self.bar.setStyleSheet("QWidget{\n"
                                   "    border-radius:20px;\n"
                                   "    background-color: rgb(140, 153, 179);;\n"
                                   "}")

        elif self.totale_consumption <= 400:
            self.bar_5.setStyleSheet("QWidget{\n"
                                     "    border-radius:20px;\n"
                                     "    background-color: rgb(140, 153, 179);;\n"
                                     "}")

        elif self.totale_consumption <= 500:
            self.bar_4.setStyleSheet("QWidget{\n"
                                     "    border-radius:20px;\n"
                                     "    background-color: rgb(140, 153, 179);;\n"
                                     "}")

        elif self.totale_consumption <= 600:
            self.bar_3.setStyleSheet("QWidget{\n"
                                     "    border-radius:20px;\n"
                                     "    background-color: rgb(140, 153, 179);;\n"
                                     "}")

        else:
            self.bar_2.setStyleSheet("QWidget{\n"
                                     "    border-radius:20px;\n"
                                     "    background-color: rgb(140, 153, 179);;\n"
                                     "}")


if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    MainWindow.resize(1922, 1048)
    ui = ConsumptionView(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())