from PyQt5.QtCore import pyqtSignal
from PyQt5.QtWidgets import QWidget, QPushButton, QVBoxLayout
from PyQt5 import QtCore, QtGui, QtWidgets

from src.backend.connection import get_current_month_consumption
from src.backend.plots import WeekPlots, MonthPlots, SixMonthPlots



class StatisticsView(QWidget):

    switch_to_consumption_page = pyqtSignal()
    switch_to_dashboard_page = pyqtSignal()
    switch_to_onduleurs_page = pyqtSignal()
    switch_to_home_page = pyqtSignal()
    switch_to_documentation_page = pyqtSignal()
    counter = 0


    def __init__(self):
        super().__init__()
        self.setObjectName("MainWindow")
        self.setStyleSheet("QFrame{\n"
                                 "    background-color: rgb(53, 58, 69);}")
        self.layout = QVBoxLayout()
        self.setObjectName("self")
        self.resize(1290, 752)
        self.setStyleSheet("background-color: rgb(41, 45, 57);")
        self.centralwidget = QtWidgets.QWidget()
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 100))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setMinimumSize(QtCore.QSize(110, 100))
        self.frame_5.setMaximumSize(QtCore.QSize(110, 100))
        self.frame_5.setStyleSheet("background-color: rgb(32, 136, 245);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout.setObjectName("gridLayout")
        self.refresh_button = QtWidgets.QPushButton(self.frame_5)
        self.refresh_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./src/icons/refresh-icon.png"), QtGui.QIcon.Normal,
                       QtGui.QIcon.Off)
        self.refresh_button.setIcon(icon)
        self.refresh_button.setIconSize(QtCore.QSize(100, 100))
        self.refresh_button.setFlat(True)
        self.refresh_button.setObjectName("refresh_button")
        self.gridLayout.addWidget(self.refresh_button, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.documentation_button = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.documentation_button.setFont(font)
        self.documentation_button.setStyleSheet("QPushButton{\n"
                                                "    color: rgb(255, 255, 255);}")
        self.documentation_button.setFlat(True)
        self.documentation_button.setObjectName("notifications_button")
        self.horizontalLayout_2.addWidget(self.documentation_button)
        self.page_title = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.page_title.setFont(font)
        self.page_title.setStyleSheet("QLabel{\n"
                                      "    color: rgb(255, 255, 255);}")
        self.page_title.setAlignment(QtCore.Qt.AlignCenter)
        self.page_title.setObjectName("page_title")
        self.horizontalLayout_2.addWidget(self.page_title)
        self.logout_button = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.logout_button.setFont(font)
        self.logout_button.setStyleSheet("QPushButton{\n"
                                         "    color: rgb(255, 255, 255);}")
        self.logout_button.setFlat(True)
        self.logout_button.setObjectName("logout_button")
        self.horizontalLayout_2.addWidget(self.logout_button)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMinimumSize(QtCore.QSize(110, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(110, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(7)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_26 = QtWidgets.QFrame(self.frame_3)
        self.frame_26.setMaximumSize(QtCore.QSize(16777215, 130))
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_26)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.dashboard_icon_button = QtWidgets.QPushButton(self.frame_26)
        self.dashboard_icon_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./src/icons/dashbord.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.dashboard_icon_button.setIcon(icon1)
        self.dashboard_icon_button.setIconSize(QtCore.QSize(70, 70))
        self.dashboard_icon_button.setFlat(True)
        self.dashboard_icon_button.setObjectName("dashboard_icon_button")
        self.verticalLayout_13.addWidget(self.dashboard_icon_button)
        self.dashboard_button1 = QtWidgets.QPushButton(self.frame_26)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.dashboard_button1.setFont(font)
        self.dashboard_button1.setStyleSheet("QPushButton{\n"
                                             "    color: rgb(255, 255, 255);}")
        self.dashboard_button1.setFlat(True)
        self.dashboard_button1.setObjectName("dashboard_button1")
        self.verticalLayout_13.addWidget(self.dashboard_button1)
        self.verticalLayout_12.addWidget(self.frame_26)
        self.frame_27 = QtWidgets.QFrame(self.frame_3)
        self.frame_27.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_27)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.consumption_icon_button = QtWidgets.QPushButton(self.frame_27)
        self.consumption_icon_button.setMaximumSize(QtCore.QSize(16777215, 50))
        self.consumption_icon_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./src/icons/Compteur-icon.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.consumption_icon_button.setIcon(icon2)
        self.consumption_icon_button.setIconSize(QtCore.QSize(70, 70))
        self.consumption_icon_button.setFlat(True)
        self.consumption_icon_button.setObjectName("consomation_icon_button")
        self.verticalLayout_14.addWidget(self.consumption_icon_button)
        self.consumption_button = QtWidgets.QPushButton(self.frame_27)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.consumption_button.setFont(font)
        self.consumption_button.setStyleSheet("QPushButton{\n"
                                              "    color: rgb(255, 255, 255);}")
        self.consumption_button.setFlat(True)
        self.consumption_button.setObjectName("consomation_button")
        self.verticalLayout_14.addWidget(self.consumption_button)
        self.verticalLayout_12.addWidget(self.frame_27)
        self.frame_28 = QtWidgets.QFrame(self.frame_3)
        self.frame_28.setMaximumSize(QtCore.QSize(16777215, 130))
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_28)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.onduleur_icon_button = QtWidgets.QPushButton(self.frame_28)
        self.onduleur_icon_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("./src/icons/onduleur-icon1.jpg"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.onduleur_icon_button.setIcon(icon3)
        self.onduleur_icon_button.setIconSize(QtCore.QSize(70, 70))
        self.onduleur_icon_button.setFlat(True)
        self.onduleur_icon_button.setObjectName("onduleur_icon_button")
        self.verticalLayout_15.addWidget(self.onduleur_icon_button)
        self.onduleur_button = QtWidgets.QPushButton(self.frame_28)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.onduleur_button.setFont(font)
        self.onduleur_button.setStyleSheet("QPushButton{\n"
                                           "    color: rgb(255, 255, 255);}")
        self.onduleur_button.setFlat(True)
        self.onduleur_button.setObjectName("onduleur_button")
        self.verticalLayout_15.addWidget(self.onduleur_button)
        self.verticalLayout_12.addWidget(self.frame_28)
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setStyleSheet("background-color: rgb(53, 58, 69);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(11)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cosomation_frame = QtWidgets.QFrame(self.frame_7)
        self.cosomation_frame.setMinimumSize(QtCore.QSize(0, 230))
        self.cosomation_frame.setStyleSheet("QFrame{\n"
                                            "    background-color: rgb(41, 45, 57);\n"
                                            "    border-radius:15px;}")
        self.cosomation_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cosomation_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cosomation_frame.setObjectName("cosomation_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.cosomation_frame)
        self.cosomation_frame.setMinimumWidth(798)
        self.verticalLayout_3.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_3.setSpacing(7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.consomation_value_label = QtWidgets.QLabel(self.cosomation_frame)
        self.consomation_value_label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.consomation_value_label.setFont(font)
        self.consomation_value_label.setStyleSheet("QLabel{\n"
                                                   "    color: rgb(255, 255, 255);}")
        self.consomation_value_label.setAlignment(QtCore.Qt.AlignCenter)
        self.consomation_value_label.setObjectName("consomation_value_label")
        self.verticalLayout_3.addWidget(self.consomation_value_label)
        self.consomation_title_label = QtWidgets.QLabel(self.cosomation_frame)
        self.consomation_title_label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.consomation_title_label.setFont(font)
        self.consomation_title_label.setStyleSheet("QLabel{\n"
                                                   "    color: rgb(255, 255, 255);}")
        self.consomation_title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.consomation_title_label.setObjectName("consomation_title_label")
        self.verticalLayout_3.addWidget(self.consomation_title_label)
        self.horizontalLayout_3.addWidget(self.cosomation_frame)
        self.price_frame = QtWidgets.QFrame(self.frame_7)
        self.price_frame.setMinimumSize(QtCore.QSize(0, 230))
        self.price_frame.setStyleSheet("QFrame{\n"
                                       "    background-color: rgb(41, 45, 57);\n"
                                       "    border-radius:15px;}")
        self.price_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.price_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.price_frame.setObjectName("price_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.price_frame)
        self.verticalLayout_4.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_4.setSpacing(7)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.price_value_label = QtWidgets.QLabel(self.price_frame)
        self.price_value_label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.price_value_label.setFont(font)
        self.price_value_label.setStyleSheet("QLabel{\n"
                                             "    color: rgb(255, 255, 255);}")
        self.price_value_label.setAlignment(QtCore.Qt.AlignCenter)
        self.price_value_label.setObjectName("price_value_label")
        self.verticalLayout_4.addWidget(self.price_value_label)
        self.price_title_label = QtWidgets.QLabel(self.price_frame)
        self.price_title_label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.price_title_label.setFont(font)
        self.price_title_label.setStyleSheet("QLabel{\n"
                                             "    color: rgb(255, 255, 255);}")
        self.price_title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.price_title_label.setObjectName("price_title_label")
        self.verticalLayout_4.addWidget(self.price_title_label)
        self.frame_6 = QtWidgets.QFrame(self.price_frame)
        self.frame_6.setMinimumSize(QtCore.QSize(500, 0))
        self.frame_6.setMaximumSize(QtCore.QSize(500, 16777215))
        self.frame_6.setStyleSheet("\n"
                                   "border-radius: 15px;\n"
                                   "")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.frame_29 = QtWidgets.QFrame(self.frame_6)
        self.frame_29.setMaximumSize(QtCore.QSize(380, 60))
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_29)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_29)
        self.lineEdit.setMaximumSize(QtCore.QSize(380, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                    "border-radius:15px;"
                                    "padding-left: 10px;")
        self.lineEdit.setText("montant pour 1W")
        self.lineEdit.setCursorPosition(17)
        self.lineEdit.setReadOnly(False)
        self.lineEdit.setPlaceholderText("")
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_17.addWidget(self.lineEdit)
        self.horizontalLayout_16.addWidget(self.frame_29)
        self.frame_30 = QtWidgets.QFrame(self.frame_6)
        self.frame_30.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_30.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_30)
        self.horizontalLayout_18.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.pushButton = QtWidgets.QPushButton(self.frame_30)
        self.pushButton.setMinimumSize(QtCore.QSize(180, 0))
        self.pushButton.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(32, 136, 245);\n"
                                      "color: rgb(255, 255, 255);\n"
                                      "border-radius: 15px;")
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_18.addWidget(self.pushButton)
        self.horizontalLayout_16.addWidget(self.frame_30)
        self.verticalLayout_4.addWidget(self.frame_6)
        self.horizontalLayout_3.addWidget(self.price_frame)
        self.verticalLayout_2.addWidget(self.frame_7)

        ##################
        #
        ##################

        self.statitisiques_frame = QtWidgets.QFrame(self.frame_4)
        self.statitisiques_frame.setStyleSheet("background-color: rgb(41, 45, 57);\n"
                                               "    border-radius:15px;")
        self.statitisiques_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.statitisiques_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.statitisiques_frame.setObjectName("statitisiques_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.statitisiques_frame)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.statitisiques_frame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.icon4 = QtGui.QIcon()
        self.icon4.addPixmap(QtGui.QPixmap("./src/icons/next-svgrepo-com (1).png"), QtGui.QIcon.Normal,
                             QtGui.QIcon.Off)
        self.icon5 = QtGui.QIcon()
        self.icon5.addPixmap(QtGui.QPixmap("./src/icons/next-svgrepo-com.png"), QtGui.QIcon.Normal,
                             QtGui.QIcon.Off)
        self.show_statistics()
        self.updateLabels()


        self.horizontalLayout.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame_2)





        self.logout_button.clicked.connect(self.switch_to_home_page.emit)
        self.documentation_button.clicked.connect(self.switch_to_documentation_page.emit)
        self.dashboard_button1.clicked.connect(self.switch_to_dashboard_page.emit)
        self.dashboard_icon_button.clicked.connect(self.switch_to_dashboard_page.emit)
        self.consumption_button.clicked.connect(self.switch_to_consumption_page.emit)
        self.consumption_icon_button.clicked.connect(self.switch_to_consumption_page.emit)
        self.onduleur_button.clicked.connect(self.switch_to_onduleurs_page.emit)
        self.onduleur_icon_button.clicked.connect(self.switch_to_onduleurs_page.emit)
        self.pushButton.clicked.connect(self.calculate_price)
        self.refresh_button.clicked.connect(self.refresh_page)


        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)


        self.layout.addWidget(self.centralwidget)
        self.layout.setContentsMargins(0, 0, 0, 0)
        self.setLayout(self.layout)


    def show_statistics(self):
        self.week_page = QtWidgets.QWidget()
        self.horizontalLayout_111 = QtWidgets.QHBoxLayout(self.week_page)
        self.horizontalLayout_111.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_111.setSpacing(0)
        self.horizontalLayout_111.setObjectName("horizontalLayout_11")
        self.frame_199 = QtWidgets.QFrame(self.week_page)
        self.frame_199.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_199.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_199.setObjectName("frame_19")
        self.horizontalLayout_155 = QtWidgets.QHBoxLayout(self.frame_199)
        self.horizontalLayout_155.setObjectName("horizontalLayout_15")
        self.frame_200 = QtWidgets.QFrame(self.frame_199)
        self.frame_200.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_200.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_200.setObjectName("frame_20")
        self.horizontalLayout_122 = QtWidgets.QHBoxLayout(self.frame_200)
        self.horizontalLayout_122.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_122.setSpacing(0)
        self.horizontalLayout_122.setObjectName("horizontalLayout_12")
        self.frame_211 = QtWidgets.QFrame(self.frame_200)
        self.frame_211.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_211.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_211.setObjectName("frame_21")
        self.verticalLayout_100 = QtWidgets.QVBoxLayout(self.frame_211)
        self.verticalLayout_100.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_100.setSpacing(0)
        self.verticalLayout_100.setObjectName("verticalLayout_10")
        self.frame_222 = QtWidgets.QFrame(self.frame_211)
        self.frame_222.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_222.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_222.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_222.setObjectName("frame_22")
        self.horizontalLayout_133 = QtWidgets.QHBoxLayout(self.frame_222)
        self.horizontalLayout_133.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_133.setSpacing(0)
        self.horizontalLayout_133.setObjectName("horizontalLayout_13")
        self.frame_233 = QtWidgets.QFrame(self.frame_222)
        self.frame_233.setMaximumSize(QtCore.QSize(190, 16777215))
        self.frame_233.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_233.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_233.setObjectName("frame_23")
        self.verticalLayout_111 = QtWidgets.QVBoxLayout(self.frame_233)
        self.verticalLayout_111.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_111.setSpacing(0)
        self.verticalLayout_111.setObjectName("verticalLayout_11")
        self.week_frame_title_2 = QtWidgets.QLabel(self.frame_233)
        self.week_frame_title_2.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.week_frame_title_2.setFont(font)
        self.week_frame_title_2.setStyleSheet("QLabel{\n"
                                              "    color: rgb(255, 255, 255);}")
        self.week_frame_title_2.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.week_frame_title_2.setObjectName("week_frame_title_4")
        self.verticalLayout_111.addWidget(self.week_frame_title_2)
        self.horizontalLayout_133.addWidget(self.frame_233)
        self.frame_244 = QtWidgets.QFrame(self.frame_222)
        self.frame_244.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_244.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_244.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_244.setObjectName("frame_24")
        self.horizontalLayout_144 = QtWidgets.QHBoxLayout(self.frame_244)
        self.horizontalLayout_144.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_144.setSpacing(0)
        self.horizontalLayout_144.setObjectName("horizontalLayout_14")
        self.backButton11 = QtWidgets.QPushButton(self.frame_244)
        self.backButton11.setFlat(True)
        self.backButton11.setObjectName("backButton1")
        self.horizontalLayout_144.addWidget(self.backButton11)
        self.week_label = QtWidgets.QLabel(self.frame_244)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.week_label.setFont(font)
        self.week_label.setStyleSheet("QLabel{\n"
                                      "    color: rgb(255, 255, 255);}")
        self.week_label.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.week_label.setObjectName("week_label_4")
        self.horizontalLayout_144.addWidget(self.week_label)
        self.week_next_button = QPushButton(self.frame_244)
        self.week_next_button.setIcon(self.icon5)
        self.week_next_button.setFlat(True)
        self.horizontalLayout_144.addWidget(self.week_next_button)
        self.horizontalLayout_133.addWidget(self.frame_244)
        self.verticalLayout_100.addWidget(self.frame_222)
        self.week_frame = QtWidgets.QFrame(self.frame_211)
        self.week_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.week_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.week_frame.setObjectName("frame_25")
        self.week_layout = QVBoxLayout(self.week_frame)
        self.week_plot_wiedget = WeekPlots()
        self.week_layout.addWidget(self.week_plot_wiedget)
        self.verticalLayout_100.addWidget(self.week_frame)
        self.horizontalLayout_122.addWidget(self.frame_211)
        self.horizontalLayout_155.addWidget(self.frame_200)
        self.horizontalLayout_111.addWidget(self.frame_199)

        # six month
        self.six_month_page = QtWidgets.QWidget()
        self.six_month_page.setObjectName("six_month_page")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.six_month_page)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_19 = QtWidgets.QFrame(self.six_month_page)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.frame_20 = QtWidgets.QFrame(self.frame_19)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_21 = QtWidgets.QFrame(self.frame_20)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_22 = QtWidgets.QFrame(self.frame_21)
        self.frame_22.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame_23 = QtWidgets.QFrame(self.frame_22)
        self.frame_23.setMaximumSize(QtCore.QSize(190, 16777215))
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.week_frame_title_4 = QtWidgets.QLabel(self.frame_23)
        self.week_frame_title_4.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.week_frame_title_4.setFont(font)
        self.week_frame_title_4.setStyleSheet("QLabel{\n"
                                              "    color: rgb(255, 255, 255);}")
        self.week_frame_title_4.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.week_frame_title_4.setObjectName("week_frame_title_4")
        self.verticalLayout_11.addWidget(self.week_frame_title_4)
        self.horizontalLayout_13.addWidget(self.frame_23)
        self.frame_24 = QtWidgets.QFrame(self.frame_22)
        self.frame_24.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_24)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.backButton1 = QtWidgets.QPushButton(self.frame_24)
        self.backButton1.setIcon(self.icon4)
        self.backButton1.setFlat(True)
        self.backButton1.setObjectName("backButton1")
        self.horizontalLayout_14.addWidget(self.backButton1)
        self.six_month_label = QtWidgets.QLabel(self.frame_24)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.six_month_label.setFont(font)
        self.six_month_label.setStyleSheet("QLabel{\n"
                                           "    color: rgb(255, 255, 255);}")
        self.six_month_label.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.six_month_label.setObjectName("week_label_4")
        self.horizontalLayout_14.addWidget(self.six_month_label)
        self.month_next_button = QPushButton(self.frame_24)
        self.month_next_button.setIcon(self.icon5)
        self.month_next_button.setFlat(True)
        self.horizontalLayout_14.addWidget(self.month_next_button)
        self.horizontalLayout_13.addWidget(self.frame_24)
        self.verticalLayout_10.addWidget(self.frame_22)
        self.six_month_frame = QtWidgets.QFrame(self.frame_21)
        self.six_month_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.six_month_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.six_month_frame.setObjectName("frame_25")
        self.six_month_layout = QVBoxLayout(self.six_month_frame)
        self.six_month_plot_widget = MonthPlots()
        self.six_month_layout.addWidget(self.six_month_plot_widget)
        self.verticalLayout_10.addWidget(self.six_month_frame)
        self.horizontalLayout_12.addWidget(self.frame_21)
        self.horizontalLayout_15.addWidget(self.frame_20)
        self.horizontalLayout_11.addWidget(self.frame_19)

        self.month_page = QtWidgets.QWidget()
        self.month_page.setObjectName("month_page")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.month_page)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_13 = QtWidgets.QFrame(self.month_page)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_14 = QtWidgets.QFrame(self.frame_13)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_15 = QtWidgets.QFrame(self.frame_14)
        self.frame_15.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_16 = QtWidgets.QFrame(self.frame_15)
        self.frame_16.setMaximumSize(QtCore.QSize(190, 16777215))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.week_frame_title_3 = QtWidgets.QLabel(self.frame_16)
        self.week_frame_title_3.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.week_frame_title_3.setFont(font)
        self.week_frame_title_3.setStyleSheet("QLabel{\n"
                                              "    color: rgb(255, 255, 255);}")
        self.week_frame_title_3.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.week_frame_title_3.setObjectName("week_frame_title_3")
        self.verticalLayout_9.addWidget(self.week_frame_title_3)
        self.horizontalLayout_8.addWidget(self.frame_16)
        self.frame_17 = QtWidgets.QFrame(self.frame_15)
        self.frame_17.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.backButton2 = QtWidgets.QPushButton(self.frame_17)
        self.backButton2.setText("")
        self.backButton2.setIcon(self.icon4)
        self.backButton2.setFlat(True)
        self.backButton2.setObjectName("backButton2")
        self.horizontalLayout_9.addWidget(self.backButton2)
        self.month_label = QtWidgets.QLabel(self.frame_17)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.month_label.setFont(font)
        self.month_label.setStyleSheet("QLabel{\n"
                                       "    color: rgb(255, 255, 255);}")
        self.month_label.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.month_label.setObjectName("week_label_3")
        self.horizontalLayout_9.addWidget(self.month_label)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_17)

        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_9.addWidget(self.pushButton_4)
        self.horizontalLayout_8.addWidget(self.frame_17)
        self.verticalLayout_8.addWidget(self.frame_15)
        self.month_frame = QtWidgets.QFrame(self.frame_14)
        self.month_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.month_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.month_frame.setObjectName("frame_18")
        self.month_plot_layout = QVBoxLayout(self.month_frame)
        self.month_plot_widget = SixMonthPlots()
        self.month_plot_layout.addWidget(self.month_plot_widget)
        self.verticalLayout_8.addWidget(self.month_frame)
        self.horizontalLayout_10.addWidget(self.frame_14)
        self.horizontalLayout_7.addWidget(self.frame_13)

        self.stackedWidget.addWidget(self.week_page)
        self.stackedWidget.addWidget(self.six_month_page)
        self.stackedWidget.addWidget(self.month_page)

        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.verticalLayout_2.addWidget(self.statitisiques_frame)

        self.week_next_button.clicked.connect(self.next)
        self.month_next_button.clicked.connect(self.next)

        self.backButton1.clicked.connect(self.back)
        self.backButton2.clicked.connect(self.back)

        self.stackedWidget.setCurrentIndex(0)


    def next(self):
        self.counter += 1
        self.stackedWidget.setCurrentIndex(self.counter)



    def back(self):
        self.counter -= 1
        self.stackedWidget.setCurrentIndex(self.counter)





    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.documentation_button.setText(_translate("MainWindow", "Documentation"))
        self.page_title.setText(_translate("MainWindow", "Statistiques"))
        self.logout_button.setText(_translate("MainWindow", "Deconnecter"))
        self.dashboard_button1.setText(_translate("MainWindow", "Tableau de\n"
                                                                "board"))
        self.consumption_button.setText(_translate("MainWindow", "Consomation"))
        self.onduleur_button.setText(_translate("MainWindow", "Onduleurs"))
        self.consomation_title_label.setText(_translate("MainWindow", "Consomation actuel"))
        self.price_title_label.setText(_translate("MainWindow", "Cout"))
        self.week_frame_title_2.setText(_translate("MainWindow", "Statistiques :"))
        self.week_label.setText(_translate("MainWindow", "Semaine"))
        self.week_frame_title_4.setText(_translate("MainWindow", "Statistiques :"))
        self.month_label.setText(_translate("MainWindow", "6-Mois"))
        self.week_frame_title_3.setText(_translate("MainWindow", "Statistiques :"))
        self.pushButton.setText(_translate("MainWindow", "Calculer"))
        self.six_month_label.setText(_translate("MainWindow", "1-Mois"))

    def delete_page(self):
        self.stackedWidget.removeWidget(self.week_page)
        self.stackedWidget.removeWidget(self.month_page)
        self.stackedWidget.removeWidget(self.six_month_page)

    totale_consumption = round(get_current_month_consumption(), 2)
    def updateLabels(self):
        try:
            self.consomation_value_label.setText("%s W" % str(self.totale_consumption))

        except:
            raise ValueError("Verifiez la connexion avec les onduleurs")


    def calculate_price(self):
        self.price_value_label.setText(None)
        try:
            self.price_value_label.setText("%s DH" % str(round((self.totale_consumption * float(self.lineEdit.text())), 2)))

        except:
            self.lineEdit.setText("entrez un nombre.")

    def empty_labels(self):
        self.consomation_value_label.setText(None)

    def refresh_page(self):
        self.delete_page()
        self.empty_labels()
        self.show_statistics()
        self.updateLabels()
        self.retranslateUi(self)