import time

from PyQt5.QtCore import pyqtSignal
from PyQt5.QtWidgets import QFrame, QMainWindow, QWidget, QGridLayout, QPushButton, QApplication, QVBoxLayout
from PyQt5 import QtCore, QtGui, QtWidgets

from backend.connection import get_min_consumption, get_max_consumption, get_avrg_consumption
from backend.dictionaries import oids, source_dic
from backend.snmp_protocole import snmp_get


class ConsumptionView(QWidget):

    switch_to_dashboard_page = pyqtSignal()
    switch_to_statistics_page = pyqtSignal()
    switch_to_onduleurs_page = pyqtSignal()
    switch_to_home_page = pyqtSignal()

    def __init__(self, mainWindow):
        super().__init__()
        mainWindow.setObjectName("Consomation")
        self.layout = QVBoxLayout()
        self.centralwidget = QtWidgets.QWidget()
        self.centralwidget.setObjectName("centralwidget")
        self.top_widger = QtWidgets.QWidget(self.centralwidget)
        self.top_widger.setGeometry(QtCore.QRect(90, 0, 1832, 90))
        self.top_widger.setStyleSheet("QWidget{\n"
                                      "    background-color: rgb(41, 45, 57);}\n"
                                      "")
        self.top_widger.setObjectName("top_widger")
        self.titile_label = QtWidgets.QLabel(self.top_widger)
        self.titile_label.setGeometry(QtCore.QRect(0, 0, 1811, 90))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.titile_label.setFont(font)
        self.titile_label.setStyleSheet("QLabel{\n"
                                        "    color: rgb(255, 255, 255);}")
        self.titile_label.setAlignment(QtCore.Qt.AlignCenter)
        self.titile_label.setObjectName("titile_label")
        self.notifications_button = QtWidgets.QPushButton(self.top_widger)
        self.notifications_button.setGeometry(QtCore.QRect(1450, 30, 161, 28))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.notifications_button.setFont(font)
        self.notifications_button.setStyleSheet("QPushButton{\n"
                                                "    color: rgb(255, 255, 255);}")
        self.notifications_button.setFlat(True)
        self.notifications_button.setObjectName("notifications_button")
        self.logout_button = QtWidgets.QPushButton(self.top_widger)
        self.logout_button.setGeometry(QtCore.QRect(1622, 30, 181, 28))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.logout_button.setFont(font)
        self.logout_button.setStyleSheet("QPushButton{\n"
                                         "    color: rgb(255, 255, 255);}")
        self.logout_button.setFlat(True)
        self.logout_button.setObjectName("logout_button")
        self.logout_button.clicked.connect(self.switch_to_home_page.emit)

        self.menu_frame = QtWidgets.QFrame(self.centralwidget)
        self.menu_frame.setGeometry(QtCore.QRect(0, 90, 90, 961))
        self.menu_frame.setStyleSheet("QWidget{\n"
                                      "    background-color: rgb(41, 45, 57);}\n"
                                      "")
        self.menu_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_frame.setObjectName("menu_frame")
        self.dashboard_icon_button = QtWidgets.QPushButton(self.menu_frame)
        self.dashboard_icon_button.setGeometry(QtCore.QRect(0, 200, 90, 79))
        self.dashboard_icon_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/dashbord.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dashboard_icon_button.setIcon(icon)
        self.dashboard_icon_button.setIconSize(QtCore.QSize(70, 70))
        self.dashboard_icon_button.setFlat(True)
        self.dashboard_icon_button.setObjectName("dashboard_icon_button")
        self.dashboard_icon_button.clicked.connect(self.switch_to_dashboard_page.emit)

        self.dashboard_button1 = QtWidgets.QPushButton(self.menu_frame)
        self.dashboard_button1.setGeometry(QtCore.QRect(0, 280, 90, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.dashboard_button1.setFont(font)
        self.dashboard_button1.setStyleSheet("QPushButton{\n"
                                             "    color: rgb(255, 255, 255);}")
        self.dashboard_button1.setFlat(True)
        self.dashboard_button1.setObjectName("dashborad1_button")
        self.dashboard_button1.clicked.connect(self.switch_to_dashboard_page.emit)

        self.dashboard_button2 = QtWidgets.QPushButton(self.menu_frame)
        self.dashboard_button2.setGeometry(QtCore.QRect(0, 300, 90, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.dashboard_button2.setFont(font)
        self.dashboard_button2.setStyleSheet("QPushButton{\n"
                                             "    color: rgb(255, 255, 255);}")
        self.dashboard_button2.setFlat(True)
        self.dashboard_button2.setObjectName("dashboard2_button")
        self.dashboard_button2.clicked.connect(self.switch_to_dashboard_page.emit)

        self.statistics_icon_button = QtWidgets.QPushButton(self.menu_frame)
        self.statistics_icon_button.setGeometry(QtCore.QRect(0, 360, 90, 79))
        self.statistics_icon_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icons/statistic-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.statistics_icon_button.setIcon(icon1)
        self.statistics_icon_button.setIconSize(QtCore.QSize(70, 70))
        self.statistics_icon_button.setFlat(True)
        self.statistics_icon_button.setObjectName("statistics_icon_button")
        self.statistics_icon_button.clicked.connect(self.switch_to_statistics_page.emit)

        self.statistics_button = QtWidgets.QPushButton(self.menu_frame)
        self.statistics_button.setGeometry(QtCore.QRect(0, 440, 90, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.statistics_button.setFont(font)
        self.statistics_button.setStyleSheet("QPushButton{\n"
                                              "    color: rgb(255, 255, 255);}")
        self.statistics_button.setFlat(True)
        self.statistics_button.setObjectName("statistics_button")
        self.statistics_button.clicked.connect(self.switch_to_statistics_page.emit)

        self.onduleur_icon_button = QtWidgets.QPushButton(self.menu_frame)
        self.onduleur_icon_button.setGeometry(QtCore.QRect(0, 500, 90, 79))
        self.onduleur_icon_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../icons/onduleur-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.onduleur_icon_button.setIcon(icon2)
        self.onduleur_icon_button.setIconSize(QtCore.QSize(70, 70))
        self.onduleur_icon_button.setFlat(True)
        self.onduleur_icon_button.setObjectName("onduleur_icon_button")
        self.onduleur_icon_button.clicked.connect(self.switch_to_onduleurs_page.emit)

        self.onduleur_button = QtWidgets.QPushButton(self.menu_frame)
        self.onduleur_button.setGeometry(QtCore.QRect(0, 580, 90, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.onduleur_button.setFont(font)
        self.onduleur_button.setStyleSheet("QPushButton{\n"
                                           "    color: rgb(255, 255, 255);}")
        self.onduleur_button.setFlat(True)
        self.onduleur_button.setObjectName("onduleur_button")
        self.onduleur_button.clicked.connect(self.switch_to_onduleurs_page.emit)

        self.lofo_frame = QtWidgets.QFrame(self.centralwidget)
        self.lofo_frame.setGeometry(QtCore.QRect(0, 0, 90, 90))
        self.lofo_frame.setStyleSheet("QWidget{\n"
                                      "    background-color: rgb(32, 136, 245);}")
        self.lofo_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lofo_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lofo_frame.setObjectName("lofo_frame")
        self.dashboard_main_frame = QtWidgets.QFrame(self.centralwidget)
        self.dashboard_main_frame.setGeometry(QtCore.QRect(90, 90, 1831, 961))
        self.dashboard_main_frame.setStyleSheet("QFrame{\n"
                                                "    background-color: rgb(53, 58, 69);}")
        self.dashboard_main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dashboard_main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dashboard_main_frame.setObjectName("dashboard_main_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dashboard_main_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizantal_frame1 = QtWidgets.QFrame(self.dashboard_main_frame)
        self.horizantal_frame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.horizantal_frame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.horizantal_frame1.setObjectName("horizantal_frame1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizantal_frame1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.consomation_frame = QtWidgets.QFrame(self.horizantal_frame1)
        self.consomation_frame.setStyleSheet("QFrame{\n"
                                             "    background-color: rgb(41, 45, 57);\n"
                                             "    border-radius:15px;\n"
                                             "}")
        self.consomation_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.consomation_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.consomation_frame.setObjectName("consomation_frame")
        self.title_label = QtWidgets.QLabel(self.consomation_frame)
        self.title_label.setGeometry(QtCore.QRect(10, 0, 221, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet("QLabel{\n"
                                       "    color: rgb(255, 255, 255);}")
        self.title_label.setObjectName("title_label")
        self.consomation_analogue = QtWidgets.QLabel(self.consomation_frame)
        self.consomation_analogue.setGeometry(QtCore.QRect(90, 50, 670, 600))
        self.consomation_analogue.setText("")
        self.consomation_analogue.setPixmap(QtGui.QPixmap("../icons/analogue-icon.png"))
        self.consomation_analogue.setScaledContents(True)
        self.consomation_analogue.setObjectName("consomation_analogue")

        self.valeure_label = QtWidgets.QLabel(self.consomation_frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.valeure_label.setFont(font)
        self.valeure_label.setStyleSheet("QLabel{\n"
                                         "    color: rgb(255, 255, 255);}")
        self.valeure_label.setObjectName("valeure_label")
        self.value_label = QtWidgets.QLabel(self.consomation_frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.value_label.setFont(font)
        self.value_label.setStyleSheet("QLabel{\n"
                                       "    color: rgb(255, 255, 255);}")
        self.value_label.setObjectName("value_label")
        self.moyenne_label = QtWidgets.QLabel(self.consomation_frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.moyenne_label.setFont(font)
        self.moyenne_label.setStyleSheet("QLabel{\n"
                                         "    color: rgb(255, 255, 255);}")
        self.moyenne_label.setObjectName("moyenne_label")
        self.average_label = QtWidgets.QLabel(self.consomation_frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.average_label.setFont(font)
        self.average_label.setStyleSheet("QLabel{\n"
                                         "    color: rgb(255, 255, 255);}")
        self.average_label.setObjectName("average_label")
        self.mini_label = QtWidgets.QLabel(self.consomation_frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.mini_label.setFont(font)
        self.mini_label.setStyleSheet("QLabel{\n"
                                      "    color: rgb(255, 255, 255);}")
        self.mini_label.setObjectName("mini_label")
        self.max_value_label = QtWidgets.QLabel(self.consomation_frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.max_value_label.setFont(font)
        self.max_value_label.setStyleSheet("QLabel{\n"
                                           "    color: rgb(255, 255, 255);}")
        self.max_value_label.setObjectName("max_value_label")
        self.max_label = QtWidgets.QLabel(self.consomation_frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.max_label.setFont(font)
        self.max_label.setStyleSheet("QLabel{\n"
                                     "    color: rgb(255, 255, 255);}")
        self.max_label.setObjectName("max_label")
        self.min_value_label = QtWidgets.QLabel(self.consomation_frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.min_value_label.setFont(font)
        self.min_value_label.setStyleSheet("QLabel{\n"
                                           "    color: rgb(255, 255, 255);}")
        self.min_value_label.setObjectName("min_value_label")
        self.horizontalLayout.addWidget(self.consomation_frame)
        self.horizantal_frame2 = QtWidgets.QFrame(self.horizantal_frame1)
        self.horizantal_frame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.horizantal_frame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.horizantal_frame2.setObjectName("horizantal_frame2")
        self.source_frame = QtWidgets.QFrame(self.horizantal_frame2)
        self.source_frame.setGeometry(QtCore.QRect(12, -1, 851, 81))
        self.source_frame.setStyleSheet("QFrame{\n"
                                        "    background-color: rgb(41, 45, 57);\n"
                                        "border-radius:15px;}")
        self.source_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.source_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.source_frame.setObjectName("source_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.source_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.source_label = QtWidgets.QLabel(self.source_frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.source_label.setFont(font)
        self.source_label.setStyleSheet("QLabel{\n"
                                        "    color: rgb(255, 255, 255);}")
        self.source_label.setObjectName("source_label")
        self.horizontalLayout_2.addWidget(self.source_label)
        self.source_type_label = QtWidgets.QLabel(self.source_frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.source_type_label.setFont(font)
        self.source_type_label.setStyleSheet("QLabel{\n"
                                             "    color: rgb(255, 255, 255);}")
        self.source_type_label.setObjectName("source_type_label")
        self.horizontalLayout_2.addWidget(self.source_type_label)
        self.class_energie_frame = QtWidgets.QFrame(self.horizantal_frame2)
        self.class_energie_frame.setGeometry(QtCore.QRect(12, 88, 851, 831))
        self.class_energie_frame.setStyleSheet("QFrame{\n"
                                               "    background-color: rgb(41, 45, 57);\n"
                                               "border-radius:15px;}")
        self.class_energie_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.class_energie_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.class_energie_frame.setObjectName("class_energie_frame")
        self.class_title_frame = QtWidgets.QLabel(self.class_energie_frame)
        self.class_title_frame.setGeometry(QtCore.QRect(10, 0, 271, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.class_title_frame.setFont(font)
        self.class_title_frame.setStyleSheet("QLabel{\n"
                                             "    color: rgb(255, 255, 255);}")
        self.class_title_frame.setObjectName("class_title_frame")
        self.class_g_widget = QtWidgets.QWidget(self.class_energie_frame)
        self.class_g_widget.setGeometry(QtCore.QRect(41, 716, 550, 84))
        self.class_g_widget.setStyleSheet("QWidget{\n"
                                          "    background-color: rgb(237, 27, 36);\n"
                                          "    border-radius:15px;\n"
                                          "}")
        self.class_g_widget.setObjectName("class_g_widget")
        self.label_14 = QtWidgets.QLabel(self.class_g_widget)
        self.label_14.setGeometry(QtCore.QRect(10, 0, 31, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.class_g_widget)
        self.label_15.setGeometry(QtCore.QRect(50, 0, 441, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.class_g_widget)
        self.label_16.setGeometry(QtCore.QRect(509, 0, 31, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_16.setObjectName("label_16")
        self.class_f_widget = QtWidgets.QWidget(self.class_energie_frame)
        self.class_f_widget.setGeometry(QtCore.QRect(41, 625, 500, 84))
        self.class_f_widget.setStyleSheet("QWidget{\n"
                                          "    background-color: #F37022;\n"
                                          "    border-radius:15px;\n"
                                          "}")
        self.class_f_widget.setObjectName("class_f_widget")
        self.label_19 = QtWidgets.QLabel(self.class_f_widget)
        self.label_19.setGeometry(QtCore.QRect(10, 0, 31, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_19.setObjectName("label_19")
        self.label_25 = QtWidgets.QLabel(self.class_f_widget)
        self.label_25.setGeometry(QtCore.QRect(459, 0, 31, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_25.setObjectName("label_25")
        self.label_31 = QtWidgets.QLabel(self.class_f_widget)
        self.label_31.setGeometry(QtCore.QRect(40, 0, 411, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.class_e_widget = QtWidgets.QWidget(self.class_energie_frame)
        self.class_e_widget.setGeometry(QtCore.QRect(41, 534, 450, 84))
        self.class_e_widget.setStyleSheet("QWidget{\n"
                                          "    background-color: #FDB813;\n"
                                          "    border-radius:15px;\n"
                                          "}")
        self.class_e_widget.setObjectName("class_e_widget")
        self.label_21 = QtWidgets.QLabel(self.class_e_widget)
        self.label_21.setGeometry(QtCore.QRect(10, 0, 31, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_21.setObjectName("label_21")
        self.label_26 = QtWidgets.QLabel(self.class_e_widget)
        self.label_26.setGeometry(QtCore.QRect(409, 0, 31, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_26.setObjectName("label_26")
        self.label_32 = QtWidgets.QLabel(self.class_e_widget)
        self.label_32.setGeometry(QtCore.QRect(40, 0, 361, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.class_b_widget = QtWidgets.QWidget(self.class_energie_frame)
        self.class_b_widget.setGeometry(QtCore.QRect(41, 262, 300, 84))
        self.class_b_widget.setStyleSheet("QWidget{\n"
                                          "    background-color: #4DB749;\n"
                                          "    border-radius:15px;\n"
                                          "}")
        self.class_b_widget.setObjectName("class_b_widget")
        self.label_24 = QtWidgets.QLabel(self.class_b_widget)
        self.label_24.setGeometry(QtCore.QRect(10, 0, 31, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_24.setObjectName("label_24")
        self.label_29 = QtWidgets.QLabel(self.class_b_widget)
        self.label_29.setGeometry(QtCore.QRect(259, 0, 31, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_29.setObjectName("label_29")
        self.label_35 = QtWidgets.QLabel(self.class_b_widget)
        self.label_35.setGeometry(QtCore.QRect(40, 0, 211, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.class_d_widget = QtWidgets.QWidget(self.class_energie_frame)
        self.class_d_widget.setGeometry(QtCore.QRect(41, 444, 400, 83))
        self.class_d_widget.setStyleSheet("QWidget{\n"
                                          "    background-color: #FFF001;\n"
                                          "    border-radius:15px;\n"
                                          "}")
        self.class_d_widget.setObjectName("class_d_widget")
        self.label_22 = QtWidgets.QLabel(self.class_d_widget)
        self.label_22.setGeometry(QtCore.QRect(10, 0, 31, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_22.setObjectName("label_22")
        self.label_27 = QtWidgets.QLabel(self.class_d_widget)
        self.label_27.setGeometry(QtCore.QRect(359, 0, 31, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_27.setObjectName("label_27")
        self.label_33 = QtWidgets.QLabel(self.class_d_widget)
        self.label_33.setGeometry(QtCore.QRect(40, 0, 311, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.class_c_widget = QtWidgets.QWidget(self.class_energie_frame)
        self.class_c_widget.setGeometry(QtCore.QRect(41, 353, 350, 84))
        self.class_c_widget.setStyleSheet("QWidget{\n"
                                          "    background-color: #86962E;\n"
                                          "    border-radius:15px;\n"
                                          "}")
        self.class_c_widget.setObjectName("class_c_widget")
        self.label_23 = QtWidgets.QLabel(self.class_c_widget)
        self.label_23.setGeometry(QtCore.QRect(10, 0, 31, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_23.setObjectName("label_23")
        self.label_28 = QtWidgets.QLabel(self.class_c_widget)
        self.label_28.setGeometry(QtCore.QRect(309, 0, 31, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_28.setObjectName("label_28")
        self.label_34 = QtWidgets.QLabel(self.class_c_widget)
        self.label_34.setGeometry(QtCore.QRect(40, 0, 261, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.class_a_widget = QtWidgets.QWidget(self.class_energie_frame)
        self.class_a_widget.setGeometry(QtCore.QRect(41, 171, 250, 84))
        self.class_a_widget.setStyleSheet("QWidget{\n"
                                          "    background-color: #01A552;\n"
                                          "    border-radius:15px;\n"
                                          "}")
        self.class_a_widget.setObjectName("class_a_widget")
        self.label_12 = QtWidgets.QLabel(self.class_a_widget)
        self.label_12.setGeometry(QtCore.QRect(0, 0, 31, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_12.setObjectName("label_12")
        self.label_30 = QtWidgets.QLabel(self.class_a_widget)
        self.label_30.setGeometry(QtCore.QRect(209, 0, 31, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_30.setObjectName("label_30")
        self.label_36 = QtWidgets.QLabel(self.class_a_widget)
        self.label_36.setGeometry(QtCore.QRect(40, 0, 161, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.bar = QtWidgets.QWidget(self.class_energie_frame)
        self.bar.setGeometry(QtCore.QRect(800, 150, 20, 651))
        self.bar.setStyleSheet("QWidget{\n"
                               "    border-radius:20px;\n"
                               "    background-color: rgb(140, 153, 179);\n"
                               "}")
        self.bar.setObjectName("bar")
        self.bar2 = QtWidgets.QWidget(self.class_energie_frame)
        self.bar2.setGeometry(QtCore.QRect(660, 660, 141, 31))
        self.bar2.setStyleSheet("QWidget{\n"
                                "    background-color: rgb(140, 153, 179);}")
        self.bar2.setObjectName("bar2")
        self.horizontalLayout.addWidget(self.horizantal_frame2)
        self.verticalLayout.addWidget(self.horizantal_frame1)

        self.valeure_label.move(241, 701)
        self.max_label.move(241, 748)
        self.moyenne_label.move(241, 795)
        self.mini_label.move(241, 842)

        self.value_label.move(440, 701)
        self.max_value_label.move(440, 748)
        self.average_label.move(440, 795)
        self.min_value_label.move(440, 842)

        self.updateLabels()

        mainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(mainWindow)

        self.layout.addWidget(self.centralwidget)
        self.layout.setContentsMargins(0, 0, 0, 0)
        self.setLayout(self.layout)

    last_consumption = 0
    last_source = None

    def updateLabels(self):
        consumption = round(float(snmp_get(oids.get("outputWatt"))) * 5/60, 2)
        source = snmp_get(oids.get("source"))
        self.min_value_label.setText("%s W" % str(round(get_min_consumption(), 2)))
        self.max_value_label.setText("%s W" % str(round(get_max_consumption(), 2)))
        self.average_label.setText("%s W" % str(round(get_avrg_consumption(), 2)))
        self.min_value_label.adjustSize()
        self.average_label.adjustSize()
        self.source_type_label.adjustSize()

        # while True:
        if self.last_consumption != consumption:
            self.value_label.setText("%s W" % str(consumption))
            self.value_label.adjustSize()

            if consumption < get_min_consumption():
                self.max_value_label.setText("%s W" % str(consumption))
                self.min_value_label.adjustSize()

            if consumption > get_max_consumption():
                self.average_label.setText("%s W" % str(consumption))
                self.average_label.adjustSize()

        if self.last_source != source:
                self.source_type_label.setText(source_dic.get(source))
                self.source_type_label.adjustSize()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titile_label.setText(_translate("MainWindow", "Consomation"))
        self.notifications_button.setText(_translate("MainWindow", "Notifications"))
        self.logout_button.setText(_translate("MainWindow", "Deconnecter"))
        self.dashboard_button1.setText(_translate("MainWindow", "Tableau"))
        self.dashboard_button2.setText(_translate("MainWindow", "de bord"))
        self.statistics_button.setText(_translate("MainWindow", "Statistiques"))
        self.onduleur_button.setText(_translate("MainWindow", "Onduleurs"))
        self.title_label.setText(_translate("MainWindow", "Consomation :"))
        self.valeure_label.setText(_translate("MainWindow", "Valeure :"))
        self.moyenne_label.setText(_translate("MainWindow", "Moyenne :"))
        self.mini_label.setText(_translate("MainWindow", "Minimume :"))
        self.max_label.setText(_translate("MainWindow", "Maximume :"))
        self.source_label.setText(_translate("MainWindow", "Source :"))
        self.class_title_frame.setText(_translate("MainWindow", "Classe d\'energie :"))
        self.label_14.setText(_translate("MainWindow", ">"))
        self.label_15.setText(_translate("MainWindow", "<"))
        self.label_16.setText(_translate("MainWindow", "G"))
        self.label_19.setText(_translate("MainWindow", "<"))
        self.label_25.setText(_translate("MainWindow", "F"))
        self.label_31.setText(_translate("MainWindow", "<"))
        self.label_21.setText(_translate("MainWindow", "<"))
        self.label_26.setText(_translate("MainWindow", "E"))
        self.label_32.setText(_translate("MainWindow", "<"))
        self.label_24.setText(_translate("MainWindow", "<"))
        self.label_29.setText(_translate("MainWindow", "B"))
        self.label_35.setText(_translate("MainWindow", "<"))
        self.label_22.setText(_translate("MainWindow", "<"))
        self.label_27.setText(_translate("MainWindow", "D"))
        self.label_33.setText(_translate("MainWindow", "<"))
        self.label_23.setText(_translate("MainWindow", "<"))
        self.label_28.setText(_translate("MainWindow", "C"))
        self.label_34.setText(_translate("MainWindow", "<"))
        self.label_12.setText(_translate("MainWindow", "<"))
        self.label_30.setText(_translate("MainWindow", "A"))
        self.label_36.setText(_translate("MainWindow", "<"))



if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    MainWindow.resize(1922, 1048)
    ui = ConsumptionView(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())