import threading

from PyQt5.QtCore import pyqtSignal, Qt, QTimer, QCoreApplication
from PyQt5.QtWidgets import QFrame, QMainWindow, QWidget, QGridLayout, QPushButton, QApplication, QVBoxLayout, \
    QMessageBox
from PyQt5 import QtCore, QtGui, QtWidgets

from backend.connection import get_avrg_consumption, get_max_consumption, get_min_consumption
from backend.plots import WeekPlots, MonthPlots, SixMonthPlots
from backend.snmp_protocole import snmp_get
from backend.dictionaries import oids, status_dic, source_dic
from pysnmp.hlapi import *



class DashboardView(QWidget):
    switch_to_consumption_page = pyqtSignal()
    switch_to_statistics_page = pyqtSignal()
    switch_to_onduleurs_page = pyqtSignal()
    switch_to_home_page = pyqtSignal()
    switch_to_documentation_page = pyqtSignal()
    counter = 0

    def __init__(self):
        super().__init__()
        self.setObjectName("self")
        self.resize(1488, 815)
        self.setStyleSheet("background-color: rgb(41, 45, 57);")
        self.layout = QVBoxLayout()
        self.centralwidget = QtWidgets.QWidget()
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_2.setStyleSheet("background-color: rgb(41, 45, 57);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.refresh_frame = QtWidgets.QFrame(self.frame_2)
        self.refresh_frame.setMinimumSize(QtCore.QSize(110, 0))
        self.refresh_frame.setMaximumSize(QtCore.QSize(110, 100))
        self.refresh_frame.setStyleSheet("background-color: rgb(32, 136, 245);")
        self.refresh_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.refresh_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.refresh_frame.setObjectName("refresh_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.refresh_frame)
        self.gridLayout.setObjectName("gridLayout")
        self.refresh_button = QtWidgets.QPushButton(self.refresh_frame)
        self.refresh_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/refresh-icon.png"), QtGui.QIcon.Normal,
                       QtGui.QIcon.Off)
        self.refresh_button.setIcon(icon)
        self.refresh_button.setIconSize(QtCore.QSize(100, 100))
        self.refresh_button.setFlat(True)
        self.refresh_button.setObjectName("refresh_button")
        self.gridLayout.addWidget(self.refresh_button, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.refresh_frame)
        self.documentation_button = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.documentation_button.setFont(font)
        self.documentation_button.setStyleSheet("QPushButton{\n"
                                                  "    color: rgb(255, 255, 255);}")
        self.documentation_button.setFlat(True)
        self.documentation_button.setObjectName("notifications_button_2")
        self.horizontalLayout_2.addWidget(self.documentation_button)
        self.page_title = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.page_title.setFont(font)
        self.page_title.setStyleSheet("QLabel{\n"
                                      "    color: rgb(255, 255, 255);}")
        self.page_title.setAlignment(QtCore.Qt.AlignCenter)
        self.page_title.setObjectName("page_title")
        self.horizontalLayout_2.addWidget(self.page_title)
        self.logout_button = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.logout_button.setFont(font)
        self.logout_button.setStyleSheet("QPushButton{\n"
                                         "    color: rgb(255, 255, 255);}")
        self.logout_button.setFlat(True)
        self.logout_button.setObjectName("logout_button")
        self.horizontalLayout_2.addWidget(self.logout_button)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMinimumSize(QtCore.QSize(110, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(110, 16777215))
        self.frame_3.setStyleSheet("background-color: rgb(41, 45, 57);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_18 = QtWidgets.QFrame(self.frame_3)
        self.frame_18.setMaximumSize(QtCore.QSize(16777215, 130))
        font = QtGui.QFont()
        font.setPointSize(4)
        self.frame_18.setFont(font)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.statistiques_icon_button = QtWidgets.QPushButton(self.frame_18)
        self.statistiques_icon_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icons/statistic-icon.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.statistiques_icon_button.setIcon(icon1)
        self.statistiques_icon_button.setIconSize(QtCore.QSize(70, 70))
        self.statistiques_icon_button.setFlat(True)
        self.statistiques_icon_button.setObjectName("dashboard_icon_button")
        self.verticalLayout_14.addWidget(self.statistiques_icon_button)
        self.statistiques_button = QtWidgets.QPushButton(self.frame_18)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.statistiques_button.setFont(font)
        self.statistiques_button.setStyleSheet("QPushButton{\n"
                                             "    color: rgb(255, 255, 255);}")
        self.statistiques_button.setFlat(True)
        self.statistiques_button.setObjectName("dashboard_button1")
        self.verticalLayout_14.addWidget(self.statistiques_button)
        self.verticalLayout_11.addWidget(self.frame_18)
        self.frame_19 = QtWidgets.QFrame(self.frame_3)
        self.frame_19.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.consumption_icon_button = QtWidgets.QPushButton(self.frame_19)
        self.consumption_icon_button.setMaximumSize(QtCore.QSize(16777215, 50))
        self.consumption_icon_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../icons/compeut-icon-png.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.consumption_icon_button.setIcon(icon2)
        self.consumption_icon_button.setIconSize(QtCore.QSize(70, 70))
        self.consumption_icon_button.setFlat(True)
        self.consumption_icon_button.setObjectName("consomation_icon_button")
        self.verticalLayout_13.addWidget(self.consumption_icon_button)
        self.consumption_button = QtWidgets.QPushButton(self.frame_19)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.consumption_button.setFont(font)
        self.consumption_button.setStyleSheet("QPushButton{\n"
                                              "    color: rgb(255, 255, 255);}")
        self.consumption_button.setFlat(True)
        self.consumption_button.setObjectName("consomation_button")
        self.verticalLayout_13.addWidget(self.consumption_button)
        self.verticalLayout_11.addWidget(self.frame_19)
        self.frame_20 = QtWidgets.QFrame(self.frame_3)
        self.frame_20.setMaximumSize(QtCore.QSize(16777215, 130))
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.onduleurs_icon_button = QtWidgets.QPushButton(self.frame_20)
        self.onduleurs_icon_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../icons/onduleur-icon1.jpg"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.onduleurs_icon_button.setIcon(icon3)
        self.onduleurs_icon_button.setIconSize(QtCore.QSize(70, 70))
        self.onduleurs_icon_button.setFlat(True)
        self.onduleurs_icon_button.setObjectName("onduleurs_icon_button")
        self.verticalLayout_12.addWidget(self.onduleurs_icon_button)
        self.onduleurs_buttons = QtWidgets.QPushButton(self.frame_20)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.onduleurs_buttons.setFont(font)
        self.onduleurs_buttons.setStyleSheet("QPushButton{\n"
                                             "    color: rgb(255, 255, 255);}")
        self.onduleurs_buttons.setFlat(True)
        self.onduleurs_buttons.setObjectName("onduleurs_buttons")
        self.verticalLayout_12.addWidget(self.onduleurs_buttons)
        self.verticalLayout_11.addWidget(self.frame_20)
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setStyleSheet("background-color: rgb(53, 58, 69);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 0)
        self.horizontalLayout_3.setSpacing(11)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.consomation_frame = QtWidgets.QFrame(self.frame_6)
        self.consomation_frame.setStyleSheet("QFrame{\n"
                                             "    background-color: rgb(41, 45, 57);\n"
                                             "    border-radius:15px;\n"
                                             "}")
        self.consomation_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.consomation_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.consomation_frame.setObjectName("consomation_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.consomation_frame)
        self.verticalLayout_4.setContentsMargins(11, 11, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.consomation_title = QtWidgets.QLabel(self.consomation_frame)
        self.consomation_title.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.consomation_title.setFont(font)
        self.consomation_title.setStyleSheet("QLabel{\n"
                                             "    color: rgb(255, 255, 255);}")
        self.consomation_title.setObjectName("consomation_title")
        self.verticalLayout_4.addWidget(self.consomation_title)
        self.frame_8 = QtWidgets.QFrame(self.consomation_frame)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_12 = QtWidgets.QFrame(self.frame_8)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.consumption_value = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.consumption_value.setFont(font)
        self.consumption_value.setStyleSheet("QLabel{\n"
                                             "    color: rgb(255, 255, 255);}")
        self.consumption_value.setObjectName("consomation_value")
        self.horizontalLayout_6.addWidget(self.consumption_value)
        self.horizontalLayout_5.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.frame_8)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.formLayout = QtWidgets.QFormLayout(self.frame_13)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(-1, -1, 0, -1)
        self.formLayout.setHorizontalSpacing(20)
        self.formLayout.setVerticalSpacing(50)
        self.formLayout.setObjectName("formLayout")
        self.moyene_label = QtWidgets.QLabel(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.moyene_label.setFont(font)
        self.moyene_label.setStyleSheet("QLabel{\n"
                                        "    color: rgb(255, 255, 255);}")
        self.moyene_label.setObjectName("moyene_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.moyene_label)
        self.avrg_value = QtWidgets.QLabel(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.avrg_value.setFont(font)
        self.avrg_value.setStyleSheet("QLabel{\n"
                                      "    color: rgb(255, 255, 255);}")
        self.avrg_value.setObjectName("avrg_value")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.avrg_value)
        self.min_label = QtWidgets.QLabel(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.min_label.setFont(font)
        self.min_label.setStyleSheet("QLabel{\n"
                                     "    color: rgb(255, 255, 255);}")
        self.min_label.setObjectName("min_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.min_label)
        self.min_consumption_value = QtWidgets.QLabel(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.min_consumption_value.setFont(font)
        self.min_consumption_value.setStyleSheet("QLabel{\n"
                                                 "    color: rgb(255, 255, 255);}")
        self.min_consumption_value.setObjectName("min_consomation_value")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.min_consumption_value)
        self.max_label = QtWidgets.QLabel(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.max_label.setFont(font)
        self.max_label.setStyleSheet("QLabel{\n"
                                     "    color: rgb(255, 255, 255);}")
        self.max_label.setObjectName("max_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.max_label)
        self.max_consumption_value = QtWidgets.QLabel(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.max_consumption_value.setFont(font)
        self.max_consumption_value.setStyleSheet("QLabel{\n"
                                                 "    color: rgb(255, 255, 255);}")
        self.max_consumption_value.setObjectName("max_consomation_value")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.max_consumption_value)
        self.horizontalLayout_5.addWidget(self.frame_13)
        self.verticalLayout_4.addWidget(self.frame_8)
        self.horizontalLayout_3.addWidget(self.consomation_frame)
        self.frame_9 = QtWidgets.QFrame(self.frame_6)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(11)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.source_frame = QtWidgets.QFrame(self.frame_9)
        self.source_frame.setMinimumSize(QtCore.QSize(0, 70))
        self.source_frame.setStyleSheet("QFrame{\n"
                                        "    background-color: rgb(41, 45, 57);\n"
                                        "border-radius:15px;}")
        self.source_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.source_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.source_frame.setObjectName("source_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.source_frame)
        self.horizontalLayout_4.setContentsMargins(11, 11, 0, 11)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.source_label = QtWidgets.QLabel(self.source_frame)
        self.source_label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.source_label.setFont(font)
        self.source_label.setStyleSheet("QLabel{\n"
                                        "    color: rgb(255, 255, 255);}")
        self.source_label.setObjectName("source_label")
        self.horizontalLayout_4.addWidget(self.source_label)
        self.source_type = QtWidgets.QLabel(self.source_frame)
        self.source_type.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.source_type.setFont(font)
        self.source_type.setStyleSheet("QLabel{\n"
                                       "    color: rgb(255, 255, 255);}")
        self.source_type.setObjectName("source_type")
        self.horizontalLayout_4.addWidget(self.source_type)
        self.verticalLayout_3.addWidget(self.source_frame)
        self.onduleurs_frame = QtWidgets.QFrame(self.frame_9)
        self.onduleurs_frame.setStyleSheet("QFrame{\n"
                                           "    background-color: rgb(41, 45, 57);\n"
                                           "border-radius:15px;}")
        self.onduleurs_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.onduleurs_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.onduleurs_frame.setObjectName("onduleurs_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.onduleurs_frame)
        self.verticalLayout_5.setContentsMargins(11, 11, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.onduleurs_title = QtWidgets.QLabel(self.onduleurs_frame)
        self.onduleurs_title.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.onduleurs_title.setFont(font)
        self.onduleurs_title.setStyleSheet("QLabel{\n"
                                           "    color: rgb(255, 255, 255);}")
        self.onduleurs_title.setObjectName("onduleurs_title")
        self.verticalLayout_5.addWidget(self.onduleurs_title)
        self.frame_10 = QtWidgets.QFrame(self.onduleurs_frame)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_14 = QtWidgets.QFrame(self.frame_10)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_7.setContentsMargins(0, 0, 30, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.puissance_value = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.puissance_value.setFont(font)
        self.puissance_value.setStyleSheet("QLabel{\n"
                                           "    color: rgb(255, 255, 255);}")
        self.puissance_value.setAlignment(QtCore.Qt.AlignCenter)
        self.puissance_value.setObjectName("puissance_value")
        self.horizontalLayout_7.addWidget(self.puissance_value)
        self.verticalLayout_8.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(self.frame_10)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_8.setContentsMargins(30, -1, -1, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_16 = QtWidgets.QFrame(self.frame_15)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.etats_label = QtWidgets.QLabel(self.frame_16)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.etats_label.setFont(font)
        self.etats_label.setStyleSheet("QLabel{\n"
                                       "    color: rgb(255, 255, 255);}")
        self.etats_label.setAlignment(QtCore.Qt.AlignCenter)
        self.etats_label.setObjectName("etats_label")
        self.verticalLayout_9.addWidget(self.etats_label)
        self.status_label = QtWidgets.QLabel(self.frame_16)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.status_label.setFont(font)
        self.status_label.setStyleSheet("QLabel{\n"
                                        "    color: rgb(255, 255, 255);}")
        self.status_label.setAlignment(QtCore.Qt.AlignCenter)
        self.status_label.setObjectName("status_label")
        self.verticalLayout_9.addWidget(self.status_label)
        self.horizontalLayout_8.addWidget(self.frame_16)
        self.frame_17 = QtWidgets.QFrame(self.frame_15)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_10.setContentsMargins(30, -1, -1, -1)
        self.verticalLayout_10.setSpacing(15)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.battery_value = QtWidgets.QLabel(self.frame_17)
        self.battery_value.setMaximumSize(QtCore.QSize(140, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.battery_value.setFont(font)
        self.battery_value.setStyleSheet("QLabel{\n"
                                         "    color: rgb(255, 255, 255);}")
        self.battery_value.setObjectName("battery_value")
        self.verticalLayout_10.addWidget(self.battery_value)
        self.onduleurs_state = QtWidgets.QLabel(self.frame_17)
        self.onduleurs_state.setMaximumSize(QtCore.QSize(140, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.onduleurs_state.setFont(font)
        self.onduleurs_state.setStyleSheet("QLabel{\n"
                                           "    color: rgb(255, 255, 255);}")
        self.onduleurs_state.setObjectName("onduleurs_state")
        self.verticalLayout_10.addWidget(self.onduleurs_state)
        self.horizontalLayout_8.addWidget(self.frame_17)
        self.verticalLayout_8.addWidget(self.frame_15)
        self.verticalLayout_5.addWidget(self.frame_10)
        self.verticalLayout_3.addWidget(self.onduleurs_frame)
        self.horizontalLayout_3.addWidget(self.frame_9)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setStyleSheet("border-radius:15px;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.logout_button.clicked.connect(self.switch_to_home_page.emit)
        self.documentation_button.clicked.connect(self.switch_to_documentation_page.emit)
        self.statistiques_icon_button.clicked.connect(self.switch_to_statistics_page.emit)
        self.statistiques_button.clicked.connect(self.switch_to_statistics_page.emit)
        self.consumption_button.clicked.connect(self.switch_to_consumption_page.emit)
        self.consumption_icon_button.clicked.connect(self.switch_to_consumption_page.emit)
        self.onduleurs_buttons.clicked.connect(self.switch_to_onduleurs_page.emit)
        self.onduleurs_icon_button.clicked.connect(self.switch_to_onduleurs_page.emit)
        self.refresh_button.clicked.connect(self.refresh_page)

        self.statitisiques_frame = QtWidgets.QFrame(self.frame_7)
        self.statitisiques_frame.setStyleSheet("background-color: rgb(41, 45, 57);\n"
                                               "border-radius:15px;")
        self.statitisiques_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.statitisiques_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.statitisiques_frame.setObjectName("statitisiques_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.statitisiques_frame)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.stackedWidget = QtWidgets.QStackedWidget(self.statitisiques_frame)
        self.stackedWidget.setStyleSheet("border-radius:15px;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.icon4 = QtGui.QIcon()

        self.icon4.addPixmap(QtGui.QPixmap("../icons/next-svgrepo-com (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon5 = QtGui.QIcon()

        self.icon5.addPixmap(QtGui.QPixmap("../icons/next-svgrepo-com.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)

        self.show_statistics()
        self.updateLabels()

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

        self.layout.addWidget(self.centralwidget)
        self.layout.setContentsMargins(0, 0, 0, 0)
        self.setLayout(self.layout)

    def show_statistics(self):
        

        # week page


        self.week_page = QtWidgets.QWidget()
        self.week_page.setStyleSheet("border-radius:15px;")
        self.week_page.setObjectName("month_page")
        self.horizontalLayout_122 = QtWidgets.QHBoxLayout(self.week_page)
        self.horizontalLayout_122.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_122.setSpacing(0)
        self.horizontalLayout_122.setObjectName("horizontalLayout_12")
        self.frame_255 = QtWidgets.QFrame(self.week_page)
        self.frame_255.setStyleSheet("border-radius:15px;")
        self.frame_255.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_255.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_255.setObjectName("frame_25")
        self.horizontalLayout_155 = QtWidgets.QHBoxLayout(self.frame_255)
        self.horizontalLayout_155.setObjectName("horizontalLayout_15")
        self.frame_266 = QtWidgets.QFrame(self.frame_255)
        self.frame_266.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_266.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_266.setObjectName("frame_26")
        self.horizontalLayout_133 = QtWidgets.QHBoxLayout(self.frame_266)
        self.horizontalLayout_133.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_133.setSpacing(0)
        self.horizontalLayout_133.setObjectName("horizontalLayout_13")
        self.frame_277 = QtWidgets.QFrame(self.frame_266)
        self.frame_277.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_277.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_277.setObjectName("frame_27")
        self.verticalLayout_166 = QtWidgets.QVBoxLayout(self.frame_277)
        self.verticalLayout_166.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_166.setSpacing(0)
        self.verticalLayout_166.setObjectName("verticalLayout_16")
        self.frame_288 = QtWidgets.QFrame(self.frame_277)
        self.frame_288.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_288.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_288.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_288.setObjectName("frame_28")
        self.horizontalLayout_144 = QtWidgets.QHBoxLayout(self.frame_288)
        self.horizontalLayout_144.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_144.setSpacing(0)
        self.horizontalLayout_144.setObjectName("horizontalLayout_14")
        self.frame_299 = QtWidgets.QFrame(self.frame_288)
        self.frame_299.setMaximumSize(QtCore.QSize(190, 16777215))
        self.frame_299.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_299.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_299.setObjectName("frame_29")
        self.verticalLayout_177 = QtWidgets.QVBoxLayout(self.frame_299)
        self.verticalLayout_177.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_177.setSpacing(0)
        self.verticalLayout_177.setObjectName("verticalLayout_17")
        self.week_frame_title = QtWidgets.QLabel(self.frame_299)
        self.week_frame_title.setMaximumSize(QtCore.QSize(16777215, 40))
        font1 = QtGui.QFont()
        font1.setPointSize(20)
        self.week_frame_title.setFont(font1)
        self.week_frame_title.setStyleSheet("QLabel{\n"
                                              "    color: rgb(255, 255, 255);}")
        self.week_frame_title.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.week_frame_title.setObjectName("week_frame_title_4")
        self.verticalLayout_177.addWidget(self.week_frame_title)
        self.horizontalLayout_144.addWidget(self.frame_299)
        self.frame_300 = QtWidgets.QFrame(self.frame_288)
        self.frame_300.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_300.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_300.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_300.setObjectName("frame_30")
        self.horizontalLayout_166 = QtWidgets.QHBoxLayout(self.frame_300)
        self.horizontalLayout_166.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_166.setSpacing(0)
        self.horizontalLayout_166.setObjectName("horizontalLayout_16")
        self.backButton11 = QtWidgets.QPushButton(self.frame_300)

        self.backButton11.setFlat(True)
        self.backButton11.setObjectName("backButton1")
        self.horizontalLayout_166.addWidget(self.backButton11)
        self.week_label = QtWidgets.QLabel(self.frame_300)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.week_label.setFont(font)
        self.week_label.setStyleSheet("QLabel{\n"
                                        "    color: rgb(255, 255, 255);}")
        self.week_label.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.week_label.setObjectName("week_label_4")
        self.horizontalLayout_166.addWidget(self.week_label)
        self.nextButton22 = QtWidgets.QPushButton(self.frame_300)
        self.nextButton22.setText("")
        self.nextButton22.setIcon(self.icon5)
        self.nextButton22.setFlat(True)
        self.nextButton22.setObjectName("nextButton2")
        self.horizontalLayout_166.addWidget(self.nextButton22)
        self.horizontalLayout_144.addWidget(self.frame_300)
        self.verticalLayout_166.addWidget(self.frame_288)
        self.week_frame = QtWidgets.QFrame(self.frame_277)
        self.week_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.week_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.week_frame.setObjectName("frame_31")
        self.verticalLayout_166.addWidget(self.week_frame)
        self.horizontalLayout_133.addWidget(self.frame_277)
        self.horizontalLayout_155.addWidget(self.frame_266)
        self.horizontalLayout_122.addWidget(self.frame_255)
        self.week_layout = QVBoxLayout(self.week_frame)
        self.week_plot_widget = WeekPlots()
        self.week_layout.addWidget(self.week_plot_widget)

        # six month page
        self.six_month_page = QtWidgets.QWidget()
        self.six_month_page.setStyleSheet("border-radius:15px;")
        self.six_month_page.setObjectName("six_month_page")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.six_month_page)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_25 = QtWidgets.QFrame(self.six_month_page)
        self.frame_25.setStyleSheet("border-radius:15px;")
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_25)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.frame_26 = QtWidgets.QFrame(self.frame_25)
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_26)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame_27 = QtWidgets.QFrame(self.frame_26)
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_27)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame_28 = QtWidgets.QFrame(self.frame_27)
        self.frame_28.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_28)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.frame_29 = QtWidgets.QFrame(self.frame_28)
        self.frame_29.setMaximumSize(QtCore.QSize(190, 16777215))
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_29)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.six_month_frame_title = QtWidgets.QLabel(self.frame_29)
        self.six_month_frame_title.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.six_month_frame_title.setFont(font)
        self.six_month_frame_title.setStyleSheet("QLabel{\n"
                                              "    color: rgb(255, 255, 255);}")
        self.six_month_frame_title.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.six_month_frame_title.setObjectName("week_frame_title_4")
        self.verticalLayout_17.addWidget(self.six_month_frame_title)
        self.horizontalLayout_14.addWidget(self.frame_29)
        self.frame_30 = QtWidgets.QFrame(self.frame_28)
        self.frame_30.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_30)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.backButton1 = QtWidgets.QPushButton(self.frame_30)
        self.backButton1.setText("")
        self.backButton1.setIcon(self.icon4)
        self.backButton1.setFlat(True)
        self.backButton1.setObjectName("backButton1")
        self.horizontalLayout_16.addWidget(self.backButton1)
        self.six_month_label = QtWidgets.QLabel(self.frame_30)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.six_month_label.setFont(font)
        self.six_month_label.setStyleSheet("QLabel{\n"
                                        "    color: rgb(255, 255, 255);}")
        self.six_month_label.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.six_month_label.setObjectName("week_label_4")
        self.horizontalLayout_16.addWidget(self.six_month_label)
        self.nextButton2 = QtWidgets.QPushButton(self.frame_30)

        self.nextButton2.setFlat(True)
        self.nextButton2.setObjectName("nextButton2")
        self.horizontalLayout_16.addWidget(self.nextButton2)
        self.horizontalLayout_14.addWidget(self.frame_30)
        self.verticalLayout_16.addWidget(self.frame_28)
        self.six_month_frame = QtWidgets.QFrame(self.frame_27)
        self.six_month_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.six_month_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.six_month_frame.setObjectName("frame_31")
        self.verticalLayout_16.addWidget(self.six_month_frame)
        self.horizontalLayout_13.addWidget(self.frame_27)
        self.horizontalLayout_15.addWidget(self.frame_26)
        self.horizontalLayout_12.addWidget(self.frame_25)
        self.six_month_layout = QVBoxLayout(self.six_month_frame)
        self.six_month_plot_widget = SixMonthPlots()
        self.six_month_layout.addWidget(self.six_month_plot_widget)

        # month page
        self.month_page = QtWidgets.QWidget()
        self.month_page.setStyleSheet("border-radius:15px;")
        self.month_page.setObjectName("month_page")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.month_page)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.frame_32 = QtWidgets.QFrame(self.month_page)
        self.frame_32.setStyleSheet("border-radius:15px;")
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_32)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.frame_33 = QtWidgets.QFrame(self.frame_32)
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_33)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.frame_34 = QtWidgets.QFrame(self.frame_33)
        self.frame_34.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_34)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.frame_35 = QtWidgets.QFrame(self.frame_34)
        self.frame_35.setMaximumSize(QtCore.QSize(190, 16777215))
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_35)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.month_frame_title = QtWidgets.QLabel(self.frame_35)
        self.month_frame_title.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.month_frame_title.setFont(font)
        self.month_frame_title.setStyleSheet("QLabel{\n"
                                              "    color: rgb(255, 255, 255);}")
        self.month_frame_title.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.month_frame_title.setObjectName("week_frame_title_3")
        self.verticalLayout_19.addWidget(self.month_frame_title)
        self.horizontalLayout_19.addWidget(self.frame_35)
        self.frame_36 = QtWidgets.QFrame(self.frame_34)
        self.frame_36.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_36)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.backButton2 = QtWidgets.QPushButton(self.frame_36)
        self.backButton2.setText("")
        self.backButton2.setIcon(self.icon4)
        self.backButton2.setFlat(True)
        self.backButton2.setObjectName("backButton2")
        self.horizontalLayout_20.addWidget(self.backButton2)
        self.month_label = QtWidgets.QLabel(self.frame_36)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.month_label.setFont(font)
        self.month_label.setStyleSheet("QLabel{\n"
                                        "    color: rgb(255, 255, 255);}")
        self.month_label.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.month_label.setObjectName("week_label_3")
        self.horizontalLayout_20.addWidget(self.month_label)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_36)
        self.pushButton_4.setText("")
        self.pushButton_4.setIcon(self.icon5)
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_20.addWidget(self.pushButton_4)
        self.horizontalLayout_19.addWidget(self.frame_36)
        self.verticalLayout_18.addWidget(self.frame_34)
        self.month_frame = QtWidgets.QFrame(self.frame_33)
        self.month_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.month_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.month_frame.setObjectName("frame_37")
        self.verticalLayout_18.addWidget(self.month_frame)
        self.horizontalLayout_18.addWidget(self.frame_33)
        self.horizontalLayout_17.addWidget(self.frame_32)
        self.month_plot_layout = QVBoxLayout(self.month_frame)
        self.month_plot_widget = MonthPlots()
        self.month_plot_layout.addWidget(self.month_plot_widget)
        self.verticalLayout_6.addWidget(self.stackedWidget)
        self.horizontalLayout_21.addWidget(self.statitisiques_frame)
        self.verticalLayout_2.addWidget(self.frame_7)
        self.horizontalLayout.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame)

        self.stackedWidget.addWidget(self.week_page)
        self.stackedWidget.addWidget(self.month_page)
        self.stackedWidget.addWidget(self.six_month_page)

        self.nextButton22.clicked.connect(self.next)
        self.pushButton_4.clicked.connect(self.next)

        self.backButton2.clicked.connect(self.back)
        self.backButton1.clicked.connect(self.back)

        self.stackedWidget.setCurrentIndex(0)

    def next(self):
        self.counter += 1
        self.stackedWidget.setCurrentIndex(self.counter)

    def back(self):
        self.counter -= 1
        self.stackedWidget.setCurrentIndex(self.counter)

    def retranslateUi(self, MainWindow):
            _translate = QtCore.QCoreApplication.translate
            MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
            self.documentation_button.setText(_translate("MainWindow", "Documentation"))
            self.page_title.setText(_translate("MainWindow", "Tableau de bord"))
            self.logout_button.setText(_translate("MainWindow", "Deconnecter"))
            self.statistiques_button.setText(_translate("MainWindow", "Statistiques"))
            self.consumption_button.setText(_translate("MainWindow", "Consomation"))
            self.onduleurs_buttons.setText(_translate("MainWindow", "Onduleurs"))
            self.consomation_title.setText(_translate("MainWindow", "Consomation :"))
            self.moyene_label.setText(_translate("MainWindow", "Moyenne :"))
            self.min_label.setText(_translate("MainWindow", "Minimume :"))
            self.max_label.setText(_translate("MainWindow", "Maximume :"))
            self.source_label.setText(_translate("MainWindow", "Source :"))
            self.onduleurs_title.setText(_translate("MainWindow", "Onduleurs :"))
            self.etats_label.setText(_translate("MainWindow", "Etats :"))
            self.status_label.setText(_translate("MainWindow", "Status :"))
            self.week_frame_title.setText(_translate("MainWindow", "Statistiques :"))
            self.week_label.setText(_translate("MainWindow", "Semaine"))
            self.six_month_frame_title.setText(_translate("MainWindow", "Statistiques :"))
            self.six_month_label.setText(_translate("MainWindow", "6-Mois"))
            self.month_frame_title.setText(_translate("MainWindow", "Statistiques :"))
            self.month_label.setText(_translate("MainWindow", "1-Mois"))


    def updateLabels(self):
        try:
            consumption = str(round(float(snmp_get(oids.get("outputWatt"), '192.168.12.113')), 2))
            source = snmp_get(oids.get("source"), '192.168.12.113')
            battery = snmp_get(oids.get("battery"), '192.168.12.113')
            status = snmp_get(oids.get("status"), '192.168.12.113')
            self.min_consumption_value.setText("%s W/h" % str(round(get_min_consumption(), 2)))
            self.max_consumption_value.setText("%s W/h" % str(round(get_max_consumption(), 2)))
            self.avrg_value.setText("%s W/h" % str(round(get_avrg_consumption(), 2)))


            self.consumption_value.setText("%s W\h" % consumption)
            self.consumption_value.adjustSize()
            self.source_type.setText(source_dic.get(source))
            self.puissance_value.setText("%s W" % consumption)
            self.puissance_value.adjustSize()
            self.battery_value.setText("%s %%" % battery)
            self.battery_value.adjustSize()
            self.onduleurs_state.setText(status_dic.get(status))
            self.onduleurs_state.adjustSize()

        except:
            raise ValueError("Verifiez la connexion avec les onduleurs")


    def delete_page(self):
        self.stackedWidget.removeWidget(self.week_page)
        self.stackedWidget.removeWidget(self.month_page)
        self.stackedWidget.removeWidget(self.six_month_page)


    def empty_labels(self):
        self.min_consumption_value.setText(None)
        self.max_consumption_value.setText(None)
        self.avrg_value.setText(None)
        self.consumption_value.setText(None)
        self.source_type.setText(None)
        self.puissance_value.setText(None)
        self.battery_value.setText(None)
        self.onduleurs_state.setText(None)

    def refresh_page(self):
        self.delete_page()
        self.empty_labels()
        self.show_statistics()
        self.updateLabels()
        self.retranslateUi(self)




