from PyQt5.QtCore import pyqtSignal, QTimer
from PyQt5.QtWidgets import QFrame, QMainWindow, QWidget, QGridLayout, QPushButton, QApplication, QVBoxLayout, \
    QMessageBox
from PyQt5 import QtCore, QtGui, QtWidgets
from backend.snmp_protocole import snmp_get
from backend.dictionaries import oids, status_dic, source_dic



class OnduleursView(QWidget):

    switch_to_consumption_page = pyqtSignal()
    switch_to_statistics_page = pyqtSignal()
    switch_to_dashboard_page = pyqtSignal()
    switch_to_home_page = pyqtSignal()
    switch_to_documentation_page = pyqtSignal()

    def __init__(self):
        super().__init__()
        self.setObjectName("MainWindow")
        self.setStyleSheet("QFrame{\n"
                                 "    background-color: rgb(53, 58, 69);}")
        self.layout = QVBoxLayout()
        self.centralwidget = QtWidgets.QWidget()
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.refresh_frame = QtWidgets.QFrame(self.centralwidget)
        self.refresh_frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.refresh_frame.setStyleSheet("background-color: rgb(41, 45, 57);")
        self.refresh_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.refresh_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.refresh_frame.setObjectName("refresh_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.refresh_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_9 = QtWidgets.QFrame(self.refresh_frame)
        self.frame_9.setMinimumSize(QtCore.QSize(110, 100))
        self.frame_9.setMaximumSize(QtCore.QSize(110, 100))
        self.frame_9.setStyleSheet("background-color: rgb(32, 136, 245);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.refresh_button = QtWidgets.QPushButton(self.frame_9)
        self.refresh_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/refresh-icon.png"), QtGui.QIcon.Normal,
                       QtGui.QIcon.Off)
        self.refresh_button.setIcon(icon)
        self.refresh_button.setIconSize(QtCore.QSize(100, 100))
        self.refresh_button.setFlat(True)
        self.refresh_button.setObjectName("refresh_button")
        self.gridLayout_6.addWidget(self.refresh_button, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_9)
        self.documentation_button = QtWidgets.QPushButton(self.refresh_frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.documentation_button.setFont(font)
        self.documentation_button.setStyleSheet("color: rgb(255, 255, 255);")
        self.documentation_button.setFlat(True)
        self.documentation_button.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.documentation_button)
        self.label = QtWidgets.QLabel(self.refresh_frame)
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label.setMaximumSize(346, 16777215)
        self.horizontalLayout_2.addWidget(self.label)
        self.logout_button = QtWidgets.QPushButton(self.refresh_frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.logout_button.setFont(font)
        self.logout_button.setStyleSheet("color: rgb(255, 255, 255);")
        self.logout_button.setFlat(True)
        self.logout_button.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.logout_button)
        self.verticalLayout.addWidget(self.refresh_frame)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMinimumSize(QtCore.QSize(110, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(110, 16777215))
        self.frame_3.setStyleSheet("background-color: rgb(41, 45, 57);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_24 = QtWidgets.QFrame(self.frame_3)
        self.frame_24.setMaximumSize(QtCore.QSize(16777215, 130))
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_24)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.dashboard_icon_buttonns = QtWidgets.QPushButton(self.frame_24)
        self.dashboard_icon_buttonns.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icons/dashbord.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.dashboard_icon_buttonns.setIcon(icon1)
        self.dashboard_icon_buttonns.setIconSize(QtCore.QSize(70, 70))
        self.dashboard_icon_buttonns.setFlat(True)
        self.dashboard_icon_buttonns.setObjectName("dashboard_icon_buttonns")
        self.verticalLayout_19.addWidget(self.dashboard_icon_buttonns)
        self.dashboard_button = QtWidgets.QPushButton(self.frame_24)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.dashboard_button.setFont(font)
        self.dashboard_button.setStyleSheet("QPushButton{\n"
                                             "    color: rgb(255, 255, 255);}")
        self.dashboard_button.setFlat(True)
        self.dashboard_button.setObjectName("dasgboard_button1")
        self.verticalLayout_19.addWidget(self.dashboard_button)
        self.verticalLayout_14.addWidget(self.frame_24)
        self.frame_25 = QtWidgets.QFrame(self.frame_3)
        self.frame_25.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.consumption_icon_button = QtWidgets.QPushButton(self.frame_25)
        self.consumption_icon_button.setMaximumSize(QtCore.QSize(16777215, 50))
        self.consumption_icon_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../icons/Compteur-icon.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.consumption_icon_button.setIcon(icon2)
        self.consumption_icon_button.setIconSize(QtCore.QSize(70, 70))
        self.consumption_icon_button.setFlat(True)
        self.consumption_icon_button.setObjectName("consomation_icon_button")
        self.verticalLayout_20.addWidget(self.consumption_icon_button)
        self.consumption_button = QtWidgets.QPushButton(self.frame_25)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.consumption_button.setFont(font)
        self.consumption_button.setStyleSheet("QPushButton{\n"
                                              "    color: rgb(255, 255, 255);}")
        self.consumption_button.setFlat(True)
        self.consumption_button.setObjectName("consomation_button")
        self.verticalLayout_20.addWidget(self.consumption_button)
        self.verticalLayout_14.addWidget(self.frame_25)
        self.frame_26 = QtWidgets.QFrame(self.frame_3)
        self.frame_26.setMaximumSize(QtCore.QSize(16777215, 130))
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_26)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.statistiques_icon_button = QtWidgets.QPushButton(self.frame_26)
        self.statistiques_icon_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../icons/statistic-icon.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.statistiques_icon_button.setIcon(icon3)
        self.statistiques_icon_button.setIconSize(QtCore.QSize(70, 70))
        self.statistiques_icon_button.setFlat(True)
        self.statistiques_icon_button.setObjectName("onduleurs_icon_button")
        self.verticalLayout_21.addWidget(self.statistiques_icon_button)
        self.statistiques_button = QtWidgets.QPushButton(self.frame_26)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.statistiques_button.setFont(font)
        self.statistiques_button.setStyleSheet("QPushButton{\n"
                                            "    color: rgb(255, 255, 255);}")
        self.statistiques_button.setFlat(True)
        self.statistiques_button.setObjectName("onduleurs_button")
        self.verticalLayout_21.addWidget(self.statistiques_button)
        self.verticalLayout_14.addWidget(self.frame_26)
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setStyleSheet("background-color: rgb(53, 58, 69);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, 7)
        self.horizontalLayout_4.setSpacing(7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.puissance_totale_frame = QtWidgets.QFrame(self.frame_6)
        self.puissance_totale_frame.setStyleSheet("QFrame{\n"
                                                  "    background-color: rgb(41, 45, 57);    \n"
                                                  "    border-radius:15px;\n"
                                                  "}")
        self.puissance_totale_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.puissance_totale_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.puissance_totale_frame.setObjectName("puissance_totale_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.puissance_totale_frame)
        self.verticalLayout_3.setContentsMargins(-1, 11, -1, 11)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.puissance_totale_value = QtWidgets.QLabel(self.puissance_totale_frame)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.puissance_totale_value.setFont(font)
        self.puissance_totale_value.setStyleSheet("QLabel{\n"
                                                  "    color: rgb(255, 255, 255);}")
        self.puissance_totale_value.setAlignment(QtCore.Qt.AlignCenter)
        self.puissance_totale_value.setObjectName("puissance_totale_value")
        self.verticalLayout_3.addWidget(self.puissance_totale_value)
        self.puissance_totale_label = QtWidgets.QLabel(self.puissance_totale_frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.puissance_totale_label.setFont(font)
        self.puissance_totale_label.setStyleSheet("QLabel{\n"
                                                  "    color: rgb(255, 255, 255);}")
        self.puissance_totale_label.setAlignment(QtCore.Qt.AlignCenter)
        self.puissance_totale_label.setObjectName("puissance_totale_label")
        self.verticalLayout_3.addWidget(self.puissance_totale_label)
        self.horizontalLayout_4.addWidget(self.puissance_totale_frame)
        self.etats_totale_frame = QtWidgets.QFrame(self.frame_6)
        self.etats_totale_frame.setStyleSheet("QFrame{\n"
                                              "    background-color: rgb(41, 45, 57);    \n"
                                              "    border-radius:15px;\n"
                                              "}")
        self.etats_totale_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.etats_totale_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.etats_totale_frame.setObjectName("etats_totale_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.etats_totale_frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.etats_totale_value_2 = QtWidgets.QLabel(self.etats_totale_frame)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.etats_totale_value_2.setFont(font)
        self.etats_totale_value_2.setStyleSheet("QLabel{\n"
                                                "    color: rgb(255, 255, 255);}")
        self.etats_totale_value_2.setAlignment(QtCore.Qt.AlignCenter)
        self.etats_totale_value_2.setObjectName("etats_totale_value_2")
        self.verticalLayout_4.addWidget(self.etats_totale_value_2)
        self.etats_totale_label_2 = QtWidgets.QLabel(self.etats_totale_frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.etats_totale_label_2.setFont(font)
        self.etats_totale_label_2.setStyleSheet("QLabel{\n"
                                                "    color: rgb(255, 255, 255);}")
        self.etats_totale_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.etats_totale_label_2.setObjectName("etats_totale_label_2")
        self.verticalLayout_4.addWidget(self.etats_totale_label_2)
        self.horizontalLayout_4.addWidget(self.etats_totale_frame)
        self.site_alarms_frame = QtWidgets.QFrame(self.frame_6)
        self.site_alarms_frame.setStyleSheet("QFrame{\n"
                                             "    background-color: rgb(41, 45, 57);    \n"
                                             "    border-radius:15px;\n"
                                             "}")
        self.site_alarms_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.site_alarms_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.site_alarms_frame.setObjectName("site_alarms_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.site_alarms_frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_44 = QtWidgets.QLabel(self.site_alarms_frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_5.addWidget(self.label_44)
        self.icons_hbos_layout_3 = QtWidgets.QHBoxLayout()
        self.icons_hbos_layout_3.setSpacing(50)
        self.icons_hbos_layout_3.setObjectName("icons_hbos_layout_3")
        self.battery_button_3 = QtWidgets.QPushButton(self.site_alarms_frame)
        self.battery_button_3.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../icons/low-battery-png.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.battery_button_3.setIcon(icon4)
        self.battery_button_3.setIconSize(QtCore.QSize(80, 80))
        self.battery_button_3.setFlat(True)
        self.battery_button_3.setObjectName("battery_button_3")
        self.icons_hbos_layout_3.addWidget(self.battery_button_3)
        self.pushButton_11 = QtWidgets.QPushButton(self.site_alarms_frame)
        self.pushButton_11.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../icons/warning.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon5)
        self.pushButton_11.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_11.setFlat(True)
        self.pushButton_11.setObjectName("pushButton_11")
        self.icons_hbos_layout_3.addWidget(self.pushButton_11)
        self.electrecite_button_3 = QtWidgets.QPushButton(self.site_alarms_frame)
        self.electrecite_button_3.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../icons/bolt-auto.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.electrecite_button_3.setIcon(icon6)
        self.electrecite_button_3.setIconSize(QtCore.QSize(80, 80))
        self.electrecite_button_3.setFlat(True)
        self.electrecite_button_3.setObjectName("electrecite_button_3")
        self.icons_hbos_layout_3.addWidget(self.electrecite_button_3)
        self.verticalLayout_5.addLayout(self.icons_hbos_layout_3)
        self.horizontalLayout_4.addWidget(self.site_alarms_frame)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.onduleur1_frame = QtWidgets.QFrame(self.frame_5)
        self.onduleur1_frame.setStyleSheet("QFrame{\n"
                                           "    background-color: rgb(41, 45, 57);    \n"
                                           "    border-radius:15px;\n"
                                           "}")
        self.onduleur1_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.onduleur1_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.onduleur1_frame.setObjectName("onduleur1_frame_6")
        self.onduleur1_frame.setMinimumSize(QtCore.QSize(0, 370))
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.onduleur1_frame)
        self.verticalLayout_10.setContentsMargins(0, 11, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_16 = QtWidgets.QFrame(self.onduleur1_frame)
        self.frame_16.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_11.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_11.setContentsMargins(10, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.onduleur2_name = QtWidgets.QLabel(self.frame_16)
        self.onduleur2_name.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.onduleur2_name.setFont(font)
        self.onduleur2_name.setStyleSheet("QLabel{\n"
                                             "    color: rgb(255, 255, 255);}")
        self.onduleur2_name.setObjectName("onduleur1_name_13")
        self.verticalLayout_11.addWidget(self.onduleur2_name)
        self.verticalLayout_10.addWidget(self.frame_16)
        self.frame_17 = QtWidgets.QFrame(self.onduleur1_frame)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_18 = QtWidgets.QFrame(self.frame_17)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.power_value_onduleur2 = QtWidgets.QLabel(self.frame_18)
        font = QtGui.QFont()
        font.setPointSize(45)
        font.setBold(True)
        font.setWeight(75)
        self.power_value_onduleur2.setFont(font)
        self.power_value_onduleur2.setStyleSheet("QLabel{\n"
                                                        "    color: rgb(255, 255, 255);}")
        self.power_value_onduleur2.setAlignment(QtCore.Qt.AlignCenter)
        self.power_value_onduleur2.setObjectName("puissance_value_onduleur1_13")
        self.verticalLayout_17.addWidget(self.power_value_onduleur2)
        self.horizontalLayout_7.addWidget(self.frame_18)
        self.frame_19 = QtWidgets.QFrame(self.frame_17)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_19)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.status_onduleur1_label_13 = QtWidgets.QLabel(self.frame_19)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.status_onduleur1_label_13.setFont(font)
        self.status_onduleur1_label_13.setStyleSheet("QLabel{\n"
                                                     "    color: rgb(255, 255, 255);}")
        self.status_onduleur1_label_13.setObjectName("status_onduleur1_label_13")
        self.gridLayout_4.addWidget(self.status_onduleur1_label_13, 1, 0, 1, 1)
        self.state_onduleur2 = QtWidgets.QLabel(self.frame_19)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.state_onduleur2.setFont(font)
        self.state_onduleur2.setStyleSheet("QLabel{\n"
                                              "    color: rgb(255, 255, 255);}")
        self.state_onduleur2.setObjectName("state_onduleur1_13")
        self.gridLayout_4.addWidget(self.state_onduleur2, 1, 1, 1, 1)
        self.etats_onduleur1_label_13 = QtWidgets.QLabel(self.frame_19)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.etats_onduleur1_label_13.setFont(font)
        self.etats_onduleur1_label_13.setStyleSheet("QLabel{\n"
                                                    "    color: rgb(255, 255, 255);}")
        self.etats_onduleur1_label_13.setObjectName("etats_onduleur1_label_13")
        self.gridLayout_4.addWidget(self.etats_onduleur1_label_13, 0, 0, 1, 1)
        self.battery_onduleur2 = QtWidgets.QLabel(self.frame_19)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.battery_onduleur2.setFont(font)
        self.battery_onduleur2.setStyleSheet("QLabel{\n"
                                                "    color: rgb(255, 255, 255);}")
        self.battery_onduleur2.setObjectName("battery_onduleur1_13")
        self.gridLayout_4.addWidget(self.battery_onduleur2, 0, 1, 1, 1)
        self.horizontalLayout_7.addWidget(self.frame_19)
        self.verticalLayout_10.addWidget(self.frame_17)
        self.gridLayout.addWidget(self.onduleur1_frame, 0, 1, 1, 1)
        self.onduleur2_frame = QtWidgets.QFrame(self.frame_5)
        self.onduleur2_frame.setMinimumSize(QtCore.QSize(0, 370))
        self.onduleur2_frame.setStyleSheet("QFrame{\n"
                                           "    background-color: rgb(41, 45, 57);    \n"
                                           "    border-radius:15px;\n"
                                           "}")
        self.onduleur2_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.onduleur2_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.onduleur2_frame.setObjectName("onduleur1_frame_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.onduleur2_frame)
        self.verticalLayout_6.setContentsMargins(0, 11, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_8 = QtWidgets.QFrame(self.onduleur2_frame)
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_7.setContentsMargins(10, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.onduleur3_name = QtWidgets.QLabel(self.frame_8)
        self.onduleur3_name.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.onduleur3_name.setFont(font)
        self.onduleur3_name.setStyleSheet("QLabel{\n"
                                             "    color: rgb(255, 255, 255);}")
        self.onduleur3_name.setObjectName("onduleur1_name_11")
        self.verticalLayout_7.addWidget(self.onduleur3_name)
        self.verticalLayout_6.addWidget(self.frame_8)
        self.frame_7 = QtWidgets.QFrame(self.onduleur2_frame)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_10 = QtWidgets.QFrame(self.frame_7)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.power_value_onduleur3 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(45)
        font.setBold(True)
        font.setWeight(75)
        self.power_value_onduleur3.setFont(font)
        self.power_value_onduleur3.setStyleSheet("QLabel{\n"
                                                        "    color: rgb(255, 255, 255);}")
        self.power_value_onduleur3.setAlignment(QtCore.Qt.AlignCenter)
        self.power_value_onduleur3.setObjectName("puissance_value_onduleur1_11")
        self.verticalLayout_16.addWidget(self.power_value_onduleur3)
        self.horizontalLayout_5.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.frame_7)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.status_onduleur1_label_11 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.status_onduleur1_label_11.setFont(font)
        self.status_onduleur1_label_11.setStyleSheet("QLabel{\n"
                                                     "    color: rgb(255, 255, 255);}")
        self.status_onduleur1_label_11.setObjectName("status_onduleur1_label_11")
        self.gridLayout_2.addWidget(self.status_onduleur1_label_11, 1, 0, 1, 1)
        self.battery_onduleur3 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.battery_onduleur3.setFont(font)
        self.battery_onduleur3.setStyleSheet("QLabel{\n"
                                                "    color: rgb(255, 255, 255);}")
        self.battery_onduleur3.setObjectName("battery_onduleur1_11")
        self.gridLayout_2.addWidget(self.battery_onduleur3, 0, 1, 1, 1)
        self.state_onduleur3 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.state_onduleur3.setFont(font)
        self.state_onduleur3.setStyleSheet("QLabel{\n"
                                              "    color: rgb(255, 255, 255);}")
        self.state_onduleur3.setObjectName("state_onduleur1_11")
        self.gridLayout_2.addWidget(self.state_onduleur3, 1, 1, 1, 1)
        self.etats_onduleur1_label_11 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.etats_onduleur1_label_11.setFont(font)
        self.etats_onduleur1_label_11.setStyleSheet("QLabel{\n"
                                                    "    color: rgb(255, 255, 255);}")
        self.etats_onduleur1_label_11.setObjectName("etats_onduleur1_label_11")
        self.gridLayout_2.addWidget(self.etats_onduleur1_label_11, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.frame_11)
        self.verticalLayout_6.addWidget(self.frame_7)
        self.gridLayout.addWidget(self.onduleur2_frame, 1, 0, 1, 1)
        self.onduleur3_frame = QtWidgets.QFrame(self.frame_5)
        self.onduleur3_frame.setMinimumSize(QtCore.QSize(0, 370))
        self.onduleur3_frame.setStyleSheet("QFrame{\n"
                                           "    background-color: rgb(41, 45, 57);    \n"
                                           "    border-radius:15px;\n"
                                           "}")
        self.onduleur3_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.onduleur3_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.onduleur3_frame.setObjectName("onduleur1_frame_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.onduleur3_frame)
        self.verticalLayout_8.setContentsMargins(0, 11, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_12 = QtWidgets.QFrame(self.onduleur3_frame)
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_9.setContentsMargins(10, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.onduleur1_name = QtWidgets.QLabel(self.frame_12)
        self.onduleur1_name.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.onduleur1_name.setFont(font)
        self.onduleur1_name.setStyleSheet("QLabel{\n"
                                             "    color: rgb(255, 255, 255);}")
        self.onduleur1_name.setObjectName("onduleur1_name_12")
        self.verticalLayout_9.addWidget(self.onduleur1_name)
        self.verticalLayout_8.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.onduleur3_frame)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_14 = QtWidgets.QFrame(self.frame_13)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.power_value_onduleur1 = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setPointSize(45)
        font.setBold(True)
        font.setWeight(75)
        self.power_value_onduleur1.setFont(font)
        self.power_value_onduleur1.setStyleSheet("QLabel{\n"
                                                        "    color: rgb(255, 255, 255);}")
        self.power_value_onduleur1.setAlignment(QtCore.Qt.AlignCenter)
        self.power_value_onduleur1.setObjectName("puissance_value_onduleur1_12")
        self.verticalLayout_15.addWidget(self.power_value_onduleur1)
        self.horizontalLayout_6.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(self.frame_13)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_15)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.state_onduleur1 = QtWidgets.QLabel(self.frame_15)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.state_onduleur1.setFont(font)
        self.state_onduleur1.setStyleSheet("QLabel{\n"
                                              "    color: rgb(255, 255, 255);}")
        self.state_onduleur1.setObjectName("state_onduleur1_12")
        self.gridLayout_3.addWidget(self.state_onduleur1, 1, 1, 1, 1)
        self.etats_onduleur1_label_12 = QtWidgets.QLabel(self.frame_15)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.etats_onduleur1_label_12.setFont(font)
        self.etats_onduleur1_label_12.setStyleSheet("QLabel{\n"
                                                    "    color: rgb(255, 255, 255);}")
        self.etats_onduleur1_label_12.setObjectName("etats_onduleur1_label_12")
        self.gridLayout_3.addWidget(self.etats_onduleur1_label_12, 0, 0, 1, 1)
        self.battery_onduleur1 = QtWidgets.QLabel(self.frame_15)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.battery_onduleur1.setFont(font)
        self.battery_onduleur1.setStyleSheet("QLabel{\n"
                                                "    color: rgb(255, 255, 255);}")
        self.battery_onduleur1.setObjectName("battery_onduleur1_12")
        self.gridLayout_3.addWidget(self.battery_onduleur1, 0, 1, 1, 1)
        self.status_onduleur1_label_12 = QtWidgets.QLabel(self.frame_15)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.status_onduleur1_label_12.setFont(font)
        self.status_onduleur1_label_12.setStyleSheet("QLabel{\n"
                                                     "    color: rgb(255, 255, 255);}")
        self.status_onduleur1_label_12.setObjectName("status_onduleur1_label_12")
        self.gridLayout_3.addWidget(self.status_onduleur1_label_12, 1, 0, 1, 1)
        self.horizontalLayout_6.addWidget(self.frame_15)
        self.verticalLayout_8.addWidget(self.frame_13)
        self.gridLayout.addWidget(self.onduleur3_frame, 0, 0, 1, 1)
        self.onduleur4_frame = QtWidgets.QFrame(self.frame_5)
        self.onduleur4_frame.setMinimumSize(QtCore.QSize(0, 370))
        self.onduleur4_frame.setStyleSheet("QFrame{\n"
                                           "    background-color: rgb(41, 45, 57);    \n"
                                           "    border-radius:15px;\n"
                                           "}")
        self.onduleur4_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.onduleur4_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.onduleur4_frame.setObjectName("onduleur1_frame_7")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.onduleur4_frame)
        self.verticalLayout_12.setContentsMargins(0, 11, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_20 = QtWidgets.QFrame(self.onduleur4_frame)
        self.frame_20.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_13.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_13.setContentsMargins(10, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.onduleur4_name = QtWidgets.QLabel(self.frame_20)
        self.onduleur4_name.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.onduleur4_name.setFont(font)
        self.onduleur4_name.setStyleSheet("QLabel{\n"
                                             "    color: rgb(255, 255, 255);}")
        self.onduleur4_name.setObjectName("onduleur1_name_14")
        self.verticalLayout_13.addWidget(self.onduleur4_name)
        self.verticalLayout_12.addWidget(self.frame_20)
        self.frame_21 = QtWidgets.QFrame(self.onduleur4_frame)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_22 = QtWidgets.QFrame(self.frame_21)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.power_value_onduleur4 = QtWidgets.QLabel(self.frame_22)
        font = QtGui.QFont()
        font.setPointSize(45)
        font.setBold(True)
        font.setWeight(75)
        self.power_value_onduleur4.setFont(font)
        self.power_value_onduleur4.setStyleSheet("QLabel{\n"
                                                        "    color: rgb(255, 255, 255);}")
        self.power_value_onduleur4.setAlignment(QtCore.Qt.AlignCenter)
        self.power_value_onduleur4.setObjectName("puissance_value_onduleur1_14")
        self.verticalLayout_18.addWidget(self.power_value_onduleur4)
        self.horizontalLayout_8.addWidget(self.frame_22)
        self.frame_23 = QtWidgets.QFrame(self.frame_21)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_23)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.battery_onduleur4 = QtWidgets.QLabel(self.frame_23)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.battery_onduleur4.setFont(font)
        self.battery_onduleur4.setStyleSheet("QLabel{\n"
                                                "    color: rgb(255, 255, 255);}")
        self.battery_onduleur4.setObjectName("battery_onduleur1_14")
        self.gridLayout_5.addWidget(self.battery_onduleur4, 0, 1, 1, 1)
        self.etats_onduleur1_label_14 = QtWidgets.QLabel(self.frame_23)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.etats_onduleur1_label_14.setFont(font)
        self.etats_onduleur1_label_14.setStyleSheet("QLabel{\n"
                                                    "    color: rgb(255, 255, 255);}")
        self.etats_onduleur1_label_14.setObjectName("etats_onduleur1_label_14")
        self.gridLayout_5.addWidget(self.etats_onduleur1_label_14, 0, 0, 1, 1)
        self.status_onduleur1_label_14 = QtWidgets.QLabel(self.frame_23)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.status_onduleur1_label_14.setFont(font)
        self.status_onduleur1_label_14.setStyleSheet("QLabel{\n"
                                                     "    color: rgb(255, 255, 255);}")
        self.status_onduleur1_label_14.setObjectName("status_onduleur1_label_14")
        self.gridLayout_5.addWidget(self.status_onduleur1_label_14, 1, 0, 1, 1)
        self.state_onduleur4 = QtWidgets.QLabel(self.frame_23)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.state_onduleur4.setFont(font)
        self.state_onduleur4.setStyleSheet("QLabel{\n"
                                              "    color: rgb(255, 255, 255);}")
        self.state_onduleur4.setObjectName("state_onduleur1_14")
        self.gridLayout_5.addWidget(self.state_onduleur4, 1, 1, 1, 1)
        self.horizontalLayout_8.addWidget(self.frame_23)
        self.verticalLayout_12.addWidget(self.frame_21)
        self.gridLayout.addWidget(self.onduleur4_frame, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.horizontalLayout.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame)


        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)
        self.updateLabels()

        self.logout_button.clicked.connect(self.switch_to_home_page.emit)
        self.documentation_button.clicked.connect(self.switch_to_documentation_page.emit)
        self.consumption_button.clicked.connect(self.switch_to_consumption_page.emit)
        self.consumption_icon_button.clicked.connect(self.switch_to_consumption_page.emit)
        self.statistiques_button.clicked.connect(self.switch_to_statistics_page.emit)
        self.statistiques_icon_button.clicked.connect(self.switch_to_statistics_page.emit)
        self.dashboard_icon_buttonns.clicked.connect(self.switch_to_dashboard_page)
        self.dashboard_button.clicked.connect(self.switch_to_dashboard_page)
        self.refresh_button.clicked.connect(self.refresh_page)

        self.layout.addWidget(self.centralwidget)
        self.layout.setContentsMargins(0, 0, 0, 0)
        self.setLayout(self.layout)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.documentation_button.setText(_translate("MainWindow", "Documentation"))
        self.label.setText(_translate("MainWindow", "Onduleurs"))
        self.logout_button.setText(_translate("MainWindow", "Deconnecter"))
        self.dashboard_button.setText(_translate("MainWindow", "Tableau de\n"
                                                                "board"))
        self.consumption_button.setText(_translate("MainWindow", "Consomation"))
        self.statistiques_button.setText(_translate("MainWindow", "Statistiques"))
        self.puissance_totale_value.setText(_translate("MainWindow", "kW"))
        self.puissance_totale_label.setText(_translate("MainWindow", "Puissance totale"))
        self.etats_totale_value_2.setText(_translate("MainWindow", "kW"))
        self.etats_totale_label_2.setText(_translate("MainWindow", "Etats totale"))
        self.label_44.setText(_translate("MainWindow", "Site alarms :"))

        self.status_onduleur1_label_13.setText(_translate("MainWindow", "Status :"))
        self.etats_onduleur1_label_13.setText(_translate("MainWindow", "Etats :"))
        self.status_onduleur1_label_11.setText(_translate("MainWindow", "Status :"))
        self.etats_onduleur1_label_11.setText(_translate("MainWindow", "Etats :"))

        self.etats_onduleur1_label_12.setText(_translate("MainWindow", "Etats :"))
        self.status_onduleur1_label_12.setText(_translate("MainWindow", "Status :"))
        self.etats_onduleur1_label_14.setText(_translate("MainWindow", "Etats :"))
        self.status_onduleur1_label_14.setText(_translate("MainWindow", "Status :"))


    def updateLabels(self):
        try:

            # Onduleur 1
            self.onduleur1_name.setText("Onduleur : %s " % snmp_get(oids.get("name"), '192.168.12.113'))
            self.power_value_onduleur1.setText("%s W" % snmp_get(oids.get("outputWatt"), '192.168.12.113'))
            self.state_onduleur1.setText(status_dic.get(snmp_get(oids.get("status"), '192.168.12.113')))
            self.battery_onduleur1.setText("%s %%" % snmp_get(oids.get("battery"), '192.168.12.113'))

            # # Onduleur 2
            # self.onduleur2_name.setText("Onduleur : %s " % snmp_get(oids.get("name"), '192.168.12.113'))
            # self.power_value_onduleur2.setText("%s W" % snmp_get(oids.get("outputWatt"), '192.168.12.113'))
            # self.state_onduleur2.setText(status_dic.get(snmp_get(oids.get("status"), '192.168.12.113')))
            # self.battery_onduleur2.setText("%s %%" % snmp_get(oids.get("battery"), '192.168.12.113'))
            #
            # # Onduleur 3
            # self.onduleur3_name.setText("Onduleur : %s " % snmp_get(oids.get("name"), '192.168.12.113'))
            # self.power_value_onduleur3.setText("%s W" % snmp_get(oids.get("outputWatt"), '192.168.12.113'))
            # self.state_onduleur3.setText(status_dic.get(snmp_get(oids.get("status"), '192.168.12.113')))
            # self.battery_onduleur3.setText("%s %%" % snmp_get(oids.get("battery"), '192.168.12.113'))
            #
            # # Onduleur 4
            # self.onduleur4_name.setText("Onduleur : %s " % snmp_get(oids.get("name"), '192.168.12.113'))
            # self.power_value_onduleur4.setText("%s W" % snmp_get(oids.get("outputWatt"), '192.168.12.113'))
            # self.state_onduleur4.setText(status_dic.get(snmp_get(oids.get("status"), '192.168.12.113')))
            # self.battery_onduleur4.setText("%s %%" % snmp_get(oids.get("battery"), '192.168.12.113'))

            self.totale_consumption = snmp_get(oids.get("outputWatt"), '192.168.12.113') # + snmp_get(oids.get("outputWatt"), 'address_ip2') + snmp_get(oids.get("outputWatt"), 'address_ip3') + snmp_get(oids.get("outputWatt"), 'address_ip4')

            # delet this line
            self.totale_battery = snmp_get(oids.get("battery"), '192.168.12.113')


            # new line
           # self.totale_battery = (snmp_get(oids.get("battery"),'192.168.12.113')   +  snmp_get(oids.get("battery"), 'address_ip2') + snmp_get(oids.get("battery"), 'address_ip3') + snmp_get(oids.get("battery"), 'address_ip4')) /4

            self.puissance_totale_value.setText("%s W" % str(self.totale_consumption))
            self.etats_totale_value_2.setText("%s %%" % str(self.totale_battery))






        except:
            raise ValueError("Verifiez la connexion avec les onduleurs")


    def refresh_page(self):
        self.updateLabels()
        self.retranslateUi(self)