from PyQt5.QtCore import pyqtSignal, QTimer
from PyQt5.QtWidgets import QFrame, QMainWindow, QWidget, QGridLayout, QPushButton, QApplication, QVBoxLayout
from PyQt5 import QtCore, QtGui, QtWidgets
from backend.snmp_protocole import snmp_get
from backend.dictionaries import oids, status_dic, source_dic

class OnduleursView(QWidget):

    switch_to_consumption_page = pyqtSignal()
    switch_to_statistics_page = pyqtSignal()
    switch_to_dashboard_page = pyqtSignal()
    switch_to_home_page = pyqtSignal()


    def __init__(self, mainWindow):
        super().__init__()
        mainWindow.setObjectName("MainWindow")
        mainWindow.resize(1922, 1048)
        mainWindow.setStyleSheet("QFrame{\n"
                                 "    background-color: rgb(53, 58, 69);}")
        self.layout = QVBoxLayout()
        self.centralwidget = QtWidgets.QWidget()
        self.centralwidget.setObjectName("centralwidget")
        self.onduleurs_frame = QtWidgets.QFrame(self.centralwidget)
        self.onduleurs_frame.setGeometry(QtCore.QRect(87, 327, 1841, 731))
        self.onduleurs_frame.setStyleSheet("QFrame{\n"
                                           "    background-color: rgb(53, 58, 69);}")
        self.onduleurs_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.onduleurs_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.onduleurs_frame.setObjectName("onduleurs_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.onduleurs_frame)
        self.gridLayout.setContentsMargins(19, 19, 19, 19)
        self.gridLayout.setSpacing(19)
        self.gridLayout.setObjectName("gridLayout")
        self.onduleur2_frame = QtWidgets.QFrame(self.onduleurs_frame)
        self.onduleur2_frame.setStyleSheet("QFrame{\n"
                                           "    background-color: rgb(41, 45, 57);    \n"
                                           "    border-radius:15px;\n"
                                           "}")
        self.onduleur2_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.onduleur2_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.onduleur2_frame.setObjectName("onduleur2_frame")
        self.analogue2 = QtWidgets.QLabel(self.onduleur2_frame)
        self.analogue2.setGeometry(QtCore.QRect(70, 50, 303, 271))
        self.analogue2.setText("")
        self.analogue2.setPixmap(QtGui.QPixmap("../icons/analogue-icon.png"))
        self.analogue2.setScaledContents(True)
        self.analogue2.setObjectName("analogue2")
        self.onduleur2_name = QtWidgets.QLabel(self.onduleur2_frame)
        self.onduleur2_name.setGeometry(QtCore.QRect(10, 5, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.onduleur2_name.setFont(font)
        self.onduleur2_name.setStyleSheet("QLabel{\n"
                                          "    color: rgb(255, 255, 255);}")
        self.onduleur2_name.setObjectName("onduleur2_name")
        self.puissane_onduleur2_label = QtWidgets.QLabel(self.onduleur2_frame)
        self.puissane_onduleur2_label.setGeometry(QtCore.QRect(511, 101, 163, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.puissane_onduleur2_label.setFont(font)
        self.puissane_onduleur2_label.setStyleSheet("QLabel{\n"
                                                    "    color: rgb(255, 255, 255);}")
        self.puissane_onduleur2_label.setObjectName("puissane_onduleur2_label")
        self.status_onduleur2_label = QtWidgets.QLabel(self.onduleur2_frame)
        self.status_onduleur2_label.setGeometry(QtCore.QRect(511, 241, 112, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.status_onduleur2_label.setFont(font)
        self.status_onduleur2_label.setStyleSheet("QLabel{\n"
                                                  "    color: rgb(255, 255, 255);}")
        self.status_onduleur2_label.setObjectName("status_onduleur2_label")
        self.state_onduleur2 = QtWidgets.QLabel(self.onduleur2_frame)
        self.state_onduleur2.setGeometry(QtCore.QRect(704, 241, 164, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.state_onduleur2.setFont(font)
        self.state_onduleur2.setStyleSheet("QLabel{\n"
                                           "    color: rgb(255, 255, 255);}")
        self.state_onduleur2.setObjectName("state_onduleur2")
        self.puissance_value_onduleur2 = QtWidgets.QLabel(self.onduleur2_frame)
        self.puissance_value_onduleur2.setGeometry(QtCore.QRect(704, 101, 164, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.puissance_value_onduleur2.setFont(font)
        self.puissance_value_onduleur2.setStyleSheet("QLabel{\n"
                                                     "    color: rgb(255, 255, 255);}")
        self.puissance_value_onduleur2.setObjectName("puissance_value_onduleur2")
        self.etats_onduleur2_label = QtWidgets.QLabel(self.onduleur2_frame)
        self.etats_onduleur2_label.setGeometry(QtCore.QRect(511, 171, 95, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.etats_onduleur2_label.setFont(font)
        self.etats_onduleur2_label.setStyleSheet("QLabel{\n"
                                                 "    color: rgb(255, 255, 255);}")
        self.etats_onduleur2_label.setObjectName("etats_onduleur2_label")
        self.battery_onduleur2 = QtWidgets.QLabel(self.onduleur2_frame)
        self.battery_onduleur2.setGeometry(QtCore.QRect(704, 171, 164, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.battery_onduleur2.setFont(font)
        self.battery_onduleur2.setStyleSheet("QLabel{\n"
                                             "    color: rgb(255, 255, 255);}")
        self.battery_onduleur2.setObjectName("battery_onduleur2")
        self.gridLayout.addWidget(self.onduleur2_frame, 0, 1, 1, 1)
        self.onduleur1_frame = QtWidgets.QFrame(self.onduleurs_frame)
        self.onduleur1_frame.setStyleSheet("QFrame{\n"
                                           "    background-color: rgb(41, 45, 57);    \n"
                                           "    border-radius:15px;\n"
                                           "}")
        self.onduleur1_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.onduleur1_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.onduleur1_frame.setObjectName("onduleur1_frame")
        self.analogue1 = QtWidgets.QLabel(self.onduleur1_frame)
        self.analogue1.setGeometry(QtCore.QRect(70, 50, 303, 271))
        self.analogue1.setText("")
        self.analogue1.setPixmap(QtGui.QPixmap("../icons/analogue-icon.png"))
        self.analogue1.setScaledContents(True)
        self.analogue1.setObjectName("analogue1")
        self.onduleur1_name = QtWidgets.QLabel(self.onduleur1_frame)
        self.onduleur1_name.setGeometry(QtCore.QRect(10, 5, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.onduleur1_name.setFont(font)
        self.onduleur1_name.setStyleSheet("QLabel{\n"
                                          "    color: rgb(255, 255, 255);}")
        self.onduleur1_name.setObjectName("onduleur1_name")
        self.puissane_onduleur1_label = QtWidgets.QLabel(self.onduleur1_frame)
        self.puissane_onduleur1_label.setGeometry(QtCore.QRect(511, 101, 163, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.puissane_onduleur1_label.setFont(font)
        self.puissane_onduleur1_label.setStyleSheet("QLabel{\n"
                                                    "    color: rgb(255, 255, 255);}")
        self.puissane_onduleur1_label.setObjectName("puissane_onduleur1_label")
        self.status_onduleur1_label = QtWidgets.QLabel(self.onduleur1_frame)
        self.status_onduleur1_label.setGeometry(QtCore.QRect(511, 241, 112, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.status_onduleur1_label.setFont(font)
        self.status_onduleur1_label.setStyleSheet("QLabel{\n"
                                                  "    color: rgb(255, 255, 255);}")
        self.status_onduleur1_label.setObjectName("status_onduleur1_label")
        self.state_onduleur1 = QtWidgets.QLabel(self.onduleur1_frame)
        self.state_onduleur1.setGeometry(QtCore.QRect(704, 241, 164, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.state_onduleur1.setFont(font)
        self.state_onduleur1.setStyleSheet("QLabel{\n"
                                           "    color: rgb(255, 255, 255);}")
        self.state_onduleur1.setObjectName("state_onduleur1")
        self.power_value_onduleur1 = QtWidgets.QLabel(self.onduleur1_frame)
        self.power_value_onduleur1.setGeometry(QtCore.QRect(704, 101, 164, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.power_value_onduleur1.setFont(font)
        self.power_value_onduleur1.setStyleSheet("QLabel{\n"
                                                     "    color: rgb(255, 255, 255);}")
        self.power_value_onduleur1.setObjectName("puissance_value_onduleur1")
        self.etats_onduleur1_label = QtWidgets.QLabel(self.onduleur1_frame)
        self.etats_onduleur1_label.setGeometry(QtCore.QRect(511, 171, 95, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.etats_onduleur1_label.setFont(font)
        self.etats_onduleur1_label.setStyleSheet("QLabel{\n"
                                                 "    color: rgb(255, 255, 255);}")
        self.etats_onduleur1_label.setObjectName("etats_onduleur1_label")
        self.battery_onduleur1 = QtWidgets.QLabel(self.onduleur1_frame)
        self.battery_onduleur1.setGeometry(QtCore.QRect(704, 171, 164, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.battery_onduleur1.setFont(font)
        self.battery_onduleur1.setStyleSheet("QLabel{\n"
                                             "    color: rgb(255, 255, 255);}")
        self.battery_onduleur1.setObjectName("battery_onduleur1")
        self.gridLayout.addWidget(self.onduleur1_frame, 0, 0, 1, 1)
        self.onduleur4_frame = QtWidgets.QFrame(self.onduleurs_frame)
        self.onduleur4_frame.setStyleSheet("QFrame{\n"
                                           "    background-color: rgb(41, 45, 57);    \n"
                                           "    border-radius:15px;\n"
                                           "}")
        self.onduleur4_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.onduleur4_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.onduleur4_frame.setObjectName("onduleur4_frame")
        self.analogue4 = QtWidgets.QLabel(self.onduleur4_frame)
        self.analogue4.setGeometry(QtCore.QRect(70, 50, 303, 271))
        self.analogue4.setText("")
        self.analogue4.setPixmap(QtGui.QPixmap("../icons/analogue-icon.png"))
        self.analogue4.setScaledContents(True)
        self.analogue4.setObjectName("analogue4")
        self.onduleur4_name = QtWidgets.QLabel(self.onduleur4_frame)
        self.onduleur4_name.setGeometry(QtCore.QRect(10, 5, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.onduleur4_name.setFont(font)
        self.onduleur4_name.setStyleSheet("QLabel{\n"
                                          "    color: rgb(255, 255, 255);}")
        self.onduleur4_name.setObjectName("onduleur4_name")
        self.puissane_onduleur4_label = QtWidgets.QLabel(self.onduleur4_frame)
        self.puissane_onduleur4_label.setGeometry(QtCore.QRect(511, 101, 163, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.puissane_onduleur4_label.setFont(font)
        self.puissane_onduleur4_label.setStyleSheet("QLabel{\n"
                                                    "    color: rgb(255, 255, 255);}")
        self.puissane_onduleur4_label.setObjectName("puissane_onduleur4_label")
        self.status_onduleur4_label = QtWidgets.QLabel(self.onduleur4_frame)
        self.status_onduleur4_label.setGeometry(QtCore.QRect(511, 241, 112, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.status_onduleur4_label.setFont(font)
        self.status_onduleur4_label.setStyleSheet("QLabel{\n"
                                                  "    color: rgb(255, 255, 255);}")
        self.status_onduleur4_label.setObjectName("status_onduleur4_label")
        self.state_onduleur4 = QtWidgets.QLabel(self.onduleur4_frame)
        self.state_onduleur4.setGeometry(QtCore.QRect(704, 241, 164, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.state_onduleur4.setFont(font)
        self.state_onduleur4.setStyleSheet("QLabel{\n"
                                           "    color: rgb(255, 255, 255);}")
        self.state_onduleur4.setObjectName("state_onduleur4")
        self.puissance_value_onduleur4 = QtWidgets.QLabel(self.onduleur4_frame)
        self.puissance_value_onduleur4.setGeometry(QtCore.QRect(704, 101, 164, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.puissance_value_onduleur4.setFont(font)
        self.puissance_value_onduleur4.setStyleSheet("QLabel{\n"
                                                     "    color: rgb(255, 255, 255);}")
        self.puissance_value_onduleur4.setObjectName("puissance_value_onduleur4")
        self.etats_onduleur4_label = QtWidgets.QLabel(self.onduleur4_frame)
        self.etats_onduleur4_label.setGeometry(QtCore.QRect(511, 171, 95, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.etats_onduleur4_label.setFont(font)
        self.etats_onduleur4_label.setStyleSheet("QLabel{\n"
                                                 "    color: rgb(255, 255, 255);}")
        self.etats_onduleur4_label.setObjectName("etats_onduleur4_label")
        self.battery_onduleur4 = QtWidgets.QLabel(self.onduleur4_frame)
        self.battery_onduleur4.setGeometry(QtCore.QRect(704, 171, 164, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.battery_onduleur4.setFont(font)
        self.battery_onduleur4.setStyleSheet("QLabel{\n"
                                             "    color: rgb(255, 255, 255);}")
        self.battery_onduleur4.setObjectName("battery_onduleur4")
        self.gridLayout.addWidget(self.onduleur4_frame, 1, 1, 1, 1)
        self.onduleur3_frame = QtWidgets.QFrame(self.onduleurs_frame)
        self.onduleur3_frame.setStyleSheet("QFrame{\n"
                                           "    background-color: rgb(41, 45, 57);    \n"
                                           "    border-radius:15px;\n"
                                           "}")
        self.onduleur3_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.onduleur3_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.onduleur3_frame.setObjectName("onduleur3_frame")
        self.analogue3 = QtWidgets.QLabel(self.onduleur3_frame)
        self.analogue3.setGeometry(QtCore.QRect(70, 50, 303, 271))
        self.analogue3.setText("")
        self.analogue3.setPixmap(QtGui.QPixmap("../icons/analogue-icon.png"))
        self.analogue3.setScaledContents(True)
        self.analogue3.setObjectName("analogue3")
        self.onduleur3_name = QtWidgets.QLabel(self.onduleur3_frame)
        self.onduleur3_name.setGeometry(QtCore.QRect(10, 5, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.onduleur3_name.setFont(font)
        self.onduleur3_name.setStyleSheet("QLabel{\n"
                                          "    color: rgb(255, 255, 255);}")
        self.onduleur3_name.setObjectName("onduleur3_name")
        self.puissance_onduleur3_label = QtWidgets.QLabel(self.onduleur3_frame)
        self.puissance_onduleur3_label.setGeometry(QtCore.QRect(511, 91, 163, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.puissance_onduleur3_label.setFont(font)
        self.puissance_onduleur3_label.setStyleSheet("QLabel{\n"
                                                     "    color: rgb(255, 255, 255);}")
        self.puissance_onduleur3_label.setObjectName("puissance_onduleur3_label")
        self.status_onduleur3_label = QtWidgets.QLabel(self.onduleur3_frame)
        self.status_onduleur3_label.setGeometry(QtCore.QRect(511, 231, 112, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.status_onduleur3_label.setFont(font)
        self.status_onduleur3_label.setStyleSheet("QLabel{\n"
                                                  "    color: rgb(255, 255, 255);}")
        self.status_onduleur3_label.setObjectName("status_onduleur3_label")
        self.state_onduleur3 = QtWidgets.QLabel(self.onduleur3_frame)
        self.state_onduleur3.setGeometry(QtCore.QRect(704, 231, 164, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.state_onduleur3.setFont(font)
        self.state_onduleur3.setStyleSheet("QLabel{\n"
                                           "    color: rgb(255, 255, 255);}")
        self.state_onduleur3.setObjectName("state_onduleur3")
        self.puissance_value_onduleur3 = QtWidgets.QLabel(self.onduleur3_frame)
        self.puissance_value_onduleur3.setGeometry(QtCore.QRect(704, 91, 164, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.puissance_value_onduleur3.setFont(font)
        self.puissance_value_onduleur3.setStyleSheet("QLabel{\n"
                                                     "    color: rgb(255, 255, 255);}")
        self.puissance_value_onduleur3.setObjectName("puissance_value_onduleur3")
        self.etats_onduleur3_label = QtWidgets.QLabel(self.onduleur3_frame)
        self.etats_onduleur3_label.setGeometry(QtCore.QRect(511, 161, 95, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.etats_onduleur3_label.setFont(font)
        self.etats_onduleur3_label.setStyleSheet("QLabel{\n"
                                                 "    color: rgb(255, 255, 255);}")
        self.etats_onduleur3_label.setObjectName("etats_onduleur3_label")
        self.battery_onduleurs3 = QtWidgets.QLabel(self.onduleur3_frame)
        self.battery_onduleurs3.setGeometry(QtCore.QRect(704, 161, 164, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.battery_onduleurs3.setFont(font)
        self.battery_onduleurs3.setStyleSheet("QLabel{\n"
                                              "    color: rgb(255, 255, 255);}")
        self.battery_onduleurs3.setObjectName("battery_onduleurs3")
        self.gridLayout.addWidget(self.onduleur3_frame, 1, 0, 1, 1)
        self.menu_frame = QtWidgets.QFrame(self.centralwidget)
        self.menu_frame.setGeometry(QtCore.QRect(0, 90, 90, 960))
        self.menu_frame.setStyleSheet("QWidget{\n"
                                      "    background-color: rgb(41, 45, 57);}\n"
                                      "")
        self.menu_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_frame.setObjectName("menu_frame")
        self.dashboard_icon_button = QtWidgets.QPushButton(self.menu_frame)
        self.dashboard_icon_button.setGeometry(QtCore.QRect(0, 200, 90, 79))
        self.dashboard_icon_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/dashbord.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dashboard_icon_button.setIcon(icon)
        self.dashboard_icon_button.setIconSize(QtCore.QSize(70, 70))
        self.dashboard_icon_button.setFlat(True)
        self.dashboard_icon_button.setObjectName("dashboard_icon_buttonns")
        self.dashboard_icon_button.clicked.connect(self.switch_to_dashboard_page.emit)

        self.dashboard_button1 = QtWidgets.QPushButton(self.menu_frame)
        self.dashboard_button1.setGeometry(QtCore.QRect(0, 280, 90, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.dashboard_button1.setFont(font)
        self.dashboard_button1.setStyleSheet("QPushButton{\n"
                                             "    color: rgb(255, 255, 255);}")
        self.dashboard_button1.setFlat(True)
        self.dashboard_button1.setObjectName("dashboard_button1")
        self.dashboard_button1.clicked.connect(self.switch_to_dashboard_page.emit)

        self.dashboard_button2 = QtWidgets.QPushButton(self.menu_frame)
        self.dashboard_button2.setGeometry(QtCore.QRect(0, 300, 90, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.dashboard_button2.setFont(font)
        self.dashboard_button2.setStyleSheet("QPushButton{\n"
                                             "    color: rgb(255, 255, 255);}")
        self.dashboard_button2.setFlat(True)
        self.dashboard_button2.setObjectName("dashboard_button2")
        self.dashboard_button2.clicked.connect(self.switch_to_dashboard_page.emit)

        self.consomation_icon_button = QtWidgets.QPushButton(self.menu_frame)
        self.consomation_icon_button.setGeometry(QtCore.QRect(0, 360, 90, 79))
        self.consomation_icon_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icons/compeut-icon-png.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.consomation_icon_button.setIcon(icon1)
        self.consomation_icon_button.setIconSize(QtCore.QSize(70, 70))
        self.consomation_icon_button.setFlat(True)
        self.consomation_icon_button.setObjectName("consomation_icon_button")
        self.consomation_icon_button.clicked.connect(self.switch_to_consumption_page.emit)

        self.consomation_button = QtWidgets.QPushButton(self.menu_frame)
        self.consomation_button.setGeometry(QtCore.QRect(0, 440, 90, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.consomation_button.setFont(font)
        self.consomation_button.setStyleSheet("QPushButton{\n"
                                              "    color: rgb(255, 255, 255);}")
        self.consomation_button.setFlat(True)
        self.consomation_button.setObjectName("consomation_button")
        self.consomation_button.clicked.connect(self.switch_to_consumption_page.emit)

        self.statistics_icon_button = QtWidgets.QPushButton(self.menu_frame)
        self.statistics_icon_button.setGeometry(QtCore.QRect(0, 500, 90, 79))
        self.statistics_icon_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../icons/statistic-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.statistics_icon_button.setIcon(icon2)
        self.statistics_icon_button.setIconSize(QtCore.QSize(70, 70))
        self.statistics_icon_button.setFlat(True)
        self.statistics_icon_button.setObjectName("onduleurs_icon_button")
        self.statistics_icon_button.clicked.connect(self.switch_to_statistics_page.emit)

        self.statistics_button = QtWidgets.QPushButton(self.menu_frame)
        self.statistics_button.setGeometry(QtCore.QRect(0, 580, 90, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.statistics_button.setFont(font)
        self.statistics_button.setStyleSheet("QPushButton{\n"
                                            "    color: rgb(255, 255, 255);}")
        self.statistics_button.setFlat(True)
        self.statistics_button.setObjectName("onduleurs_button")
        self.statistics_button.clicked.connect(self.switch_to_statistics_page.emit)

        self.top_frame = QtWidgets.QFrame(self.centralwidget)
        self.top_frame.setGeometry(QtCore.QRect(90, 90, 1833, 241))
        self.top_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame.setObjectName("top_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.puissance_totale_frame = QtWidgets.QFrame(self.top_frame)
        self.puissance_totale_frame.setStyleSheet("QFrame{\n"
                                                  "    background-color: rgb(41, 45, 57);    \n"
                                                  "    border-radius:15px;\n"
                                                  "}")
        self.puissance_totale_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.puissance_totale_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.puissance_totale_frame.setObjectName("puissance_totale_frame")
        self.puissance_totale_label = QtWidgets.QLabel(self.puissance_totale_frame)
        self.puissance_totale_label.setGeometry(QtCore.QRect(0, 150, 591, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.puissance_totale_label.setFont(font)
        self.puissance_totale_label.setStyleSheet("QLabel{\n"
                                                  "    color: rgb(255, 255, 255);}")
        self.puissance_totale_label.setAlignment(QtCore.Qt.AlignCenter)
        self.puissance_totale_label.setObjectName("puissance_totale_label")
        self.puissance_totale_value = QtWidgets.QLabel(self.puissance_totale_frame)
        self.puissance_totale_value.setGeometry(QtCore.QRect(0, 50, 601, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.puissance_totale_value.setFont(font)
        self.puissance_totale_value.setStyleSheet("QLabel{\n"
                                                  "    color: rgb(255, 255, 255);}")
        self.puissance_totale_value.setAlignment(QtCore.Qt.AlignCenter)
        self.puissance_totale_value.setObjectName("puissance_totale_value")
        self.horizontalLayout.addWidget(self.puissance_totale_frame)
        self.etats_totale_frame = QtWidgets.QFrame(self.top_frame)
        self.etats_totale_frame.setStyleSheet("QFrame{\n"
                                              "    background-color: rgb(41, 45, 57);    \n"
                                              "    border-radius:15px;\n"
                                              "}")
        self.etats_totale_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.etats_totale_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.etats_totale_frame.setObjectName("etats_totale_frame")
        self.etats_totale_label = QtWidgets.QLabel(self.etats_totale_frame)
        self.etats_totale_label.setGeometry(QtCore.QRect(0, 150, 591, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.etats_totale_label.setFont(font)
        self.etats_totale_label.setStyleSheet("QLabel{\n"
                                              "    color: rgb(255, 255, 255);}")
        self.etats_totale_label.setAlignment(QtCore.Qt.AlignCenter)
        self.etats_totale_label.setObjectName("etats_totale_label")
        self.etats_totale_value = QtWidgets.QLabel(self.etats_totale_frame)
        self.etats_totale_value.setGeometry(QtCore.QRect(0, 50, 601, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.etats_totale_value.setFont(font)
        self.etats_totale_value.setStyleSheet("QLabel{\n"
                                              "    color: rgb(255, 255, 255);}")
        self.etats_totale_value.setAlignment(QtCore.Qt.AlignCenter)
        self.etats_totale_value.setObjectName("etats_totale_value")
        self.horizontalLayout.addWidget(self.etats_totale_frame)
        self.site_alarms_frame = QtWidgets.QFrame(self.top_frame)
        self.site_alarms_frame.setStyleSheet("QFrame{\n"
                                             "    background-color: rgb(41, 45, 57);    \n"
                                             "    border-radius:15px;\n"
                                             "}")
        self.site_alarms_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.site_alarms_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.site_alarms_frame.setObjectName("site_alarms_frame")
        self.label_42 = QtWidgets.QLabel(self.site_alarms_frame)
        self.label_42.setGeometry(QtCore.QRect(10, 5, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("QLabel{\n"
                                    "    color: rgb(255, 255, 255);}")
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.widget = QtWidgets.QWidget(self.site_alarms_frame)
        self.widget.setGeometry(QtCore.QRect(0, 90, 601, 91))
        self.widget.setObjectName("widget")
        self.icons_hbos_layout = QtWidgets.QHBoxLayout(self.widget)
        self.icons_hbos_layout.setContentsMargins(0, 0, 0, 0)
        self.icons_hbos_layout.setSpacing(50)
        self.icons_hbos_layout.setObjectName("icons_hbos_layout")
        self.battery_button = QtWidgets.QPushButton(self.widget)
        self.battery_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../icons/low-battery-png.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.battery_button.setIcon(icon3)
        self.battery_button.setIconSize(QtCore.QSize(80, 80))
        self.battery_button.setFlat(True)
        self.battery_button.setObjectName("battery_button")
        self.icons_hbos_layout.addWidget(self.battery_button)
        self.pushButton_9 = QtWidgets.QPushButton(self.widget)
        self.pushButton_9.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../icons/warning.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon4)
        self.pushButton_9.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_9.setFlat(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.icons_hbos_layout.addWidget(self.pushButton_9)
        self.electrecite_button = QtWidgets.QPushButton(self.widget)
        self.electrecite_button.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../icons/bolt-auto.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.electrecite_button.setIcon(icon5)
        self.electrecite_button.setIconSize(QtCore.QSize(80, 80))
        self.electrecite_button.setFlat(True)
        self.electrecite_button.setObjectName("electrecite_button")
        self.icons_hbos_layout.addWidget(self.electrecite_button)
        self.horizontalLayout.addWidget(self.site_alarms_frame)
        self.top_widget = QtWidgets.QWidget(self.centralwidget)
        self.top_widget.setGeometry(QtCore.QRect(90, 0, 1832, 90))
        self.top_widget.setStyleSheet("QWidget{\n"
                                      "    background-color: rgb(41, 45, 57);}\n"
                                      "")
        self.top_widget.setObjectName("top_widget")
        self.page_title = QtWidgets.QLabel(self.top_widget)
        self.page_title.setGeometry(QtCore.QRect(0, 0, 1811, 90))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.page_title.setFont(font)
        self.page_title.setStyleSheet("QLabel{\n"
                                      "    color: rgb(255, 255, 255);}")
        self.page_title.setAlignment(QtCore.Qt.AlignCenter)
        self.page_title.setObjectName("page_title")
        self.notifications_button = QtWidgets.QPushButton(self.top_widget)
        self.notifications_button.setGeometry(QtCore.QRect(1450, 30, 161, 28))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.notifications_button.setFont(font)
        self.notifications_button.setStyleSheet("QPushButton{\n"
                                                "    color: rgb(255, 255, 255);}")
        self.notifications_button.setFlat(True)
        self.notifications_button.setObjectName("notifications_button")
        self.logout_button = QtWidgets.QPushButton(self.top_widget)
        self.logout_button.setGeometry(QtCore.QRect(1622, 30, 181, 28))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.logout_button.setFont(font)
        self.logout_button.setStyleSheet("QPushButton{\n"
                                         "    color: rgb(255, 255, 255);}")
        self.logout_button.setFlat(True)
        self.logout_button.setObjectName("logout_button")
        self.logout_button.clicked.connect(self.switch_to_home_page.emit)

        self.logo_frame = QtWidgets.QFrame(self.centralwidget)
        self.logo_frame.setGeometry(QtCore.QRect(0, 0, 90, 90))
        self.logo_frame.setStyleSheet("QWidget{\n"
                                      "    background-color: rgb(32, 136, 245);}")
        self.logo_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo_frame.setObjectName("logo_frame")
        self.onduleur1_name.setText(snmp_get(oids.get("name")))
        self.updateLabels()
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

        self.layout.addWidget(self.centralwidget)
        self.layout.setContentsMargins(0, 0, 0, 0)
        self.setLayout(self.layout)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.onduleur2_name.setText(_translate("MainWindow", "TextLabel :"))
        self.puissane_onduleur2_label.setText(_translate("MainWindow", "Puissance :"))
        self.status_onduleur2_label.setText(_translate("MainWindow", "Status :"))
        self.state_onduleur2.setText(_translate("MainWindow", "TextLabel"))
        self.puissance_value_onduleur2.setText(_translate("MainWindow", "TextLabel"))
        self.etats_onduleur2_label.setText(_translate("MainWindow", "Etats :"))
        self.battery_onduleur2.setText(_translate("MainWindow", "TextLabel"))
        self.puissane_onduleur1_label.setText(_translate("MainWindow", "Puissance :"))
        self.status_onduleur1_label.setText(_translate("MainWindow", "Status :"))
        self.etats_onduleur1_label.setText(_translate("MainWindow", "Etats :"))
        self.onduleur4_name.setText(_translate("MainWindow", "TextLabel :"))
        self.puissane_onduleur4_label.setText(_translate("MainWindow", "Puissance :"))
        self.status_onduleur4_label.setText(_translate("MainWindow", "Status :"))
        self.state_onduleur4.setText(_translate("MainWindow", "TextLabel"))
        self.puissance_value_onduleur4.setText(_translate("MainWindow", "TextLabel"))
        self.etats_onduleur4_label.setText(_translate("MainWindow", "Etats :"))
        self.battery_onduleur4.setText(_translate("MainWindow", "TextLabel"))
        self.onduleur3_name.setText(_translate("MainWindow", "TextLabel :"))
        self.puissance_onduleur3_label.setText(_translate("MainWindow", "Puissance :"))
        self.status_onduleur3_label.setText(_translate("MainWindow", "Status :"))
        self.state_onduleur3.setText(_translate("MainWindow", "TextLabel"))
        self.puissance_value_onduleur3.setText(_translate("MainWindow", "TextLabel"))
        self.etats_onduleur3_label.setText(_translate("MainWindow", "Etats :"))
        self.battery_onduleurs3.setText(_translate("MainWindow", "TextLabel"))
        self.dashboard_button1.setText(_translate("MainWindow", "Tableau"))
        self.dashboard_button2.setText(_translate("MainWindow", "de bord"))
        self.consomation_button.setText(_translate("MainWindow", "Consomation"))
        self.statistics_button.setText(_translate("MainWindow", "Statistiques"))
        self.puissance_totale_label.setText(_translate("MainWindow", "Puissance totale"))
        self.puissance_totale_value.setText(_translate("MainWindow", "kW"))
        self.etats_totale_label.setText(_translate("MainWindow", "Etats totale"))
        self.etats_totale_value.setText(_translate("MainWindow", "kW"))
        self.label_42.setText(_translate("MainWindow", "Site alarms :"))
        self.page_title.setText(_translate("MainWindow", "Onduleurs"))
        self.notifications_button.setText(_translate("MainWindow", "Notifications"))
        self.logout_button.setText(_translate("MainWindow", "Deconnecter"))

    timer = QTimer()
    last_power = None
    last_battery = None
    lasst_status = None

    def updateLabels(self):
        power = snmp_get(oids.get("outputWatt"))
        battery = snmp_get(oids.get("battery"))
        status = snmp_get(oids.get("status"))

        if self.last_power != power:
            self.power_value_onduleur1.setText("%s kW" % power)

        if self.last_battery != power:
            self.battery_onduleur1.setText("%s %%" % battery)

        if self.last_battery != battery:
            self.state_onduleur1.setText(status_dic.get(status))

        # if self.last_power != power or self.last_battery != power or self.last_battery != battery:
        #     self.timer.timeout.connect(self.updateLabels)
        #     self.timer.start(5000)
        #     self.last_power = power
        #     self.last_battery = battery
        #     self.status = status

