from PyQt5.QtCore import pyqtSignal
from PyQt5.QtWidgets import QFrame, QMainWindow, QWidget, QGridLayout, QPushButton, QApplication, QVBoxLayout
from PyQt5 import QtCore, QtGui, QtWidgets
from backend.plots import WeekPlots, MonthPlots, SixMonthPlots



class StatisticsView(QWidget):

    switch_to_consumption_page = pyqtSignal()
    switch_to_dashboard_page = pyqtSignal()
    switch_to_onduleurs_page = pyqtSignal()
    switch_to_home_page = pyqtSignal()
    counter = 0


    def __init__(self, mainWindow):
        super().__init__()
        mainWindow.setObjectName("MainWindow")
        mainWindow.setStyleSheet("QFrame{\n"
                                 "    background-color: rgb(53, 58, 69);}")
        self.layout = QVBoxLayout()
        self.centralwidget = QtWidgets.QWidget()
        self.centralwidget.setObjectName("centralwidget")
        self.top_widget = QtWidgets.QWidget(self.centralwidget)
        self.top_widget.setGeometry(QtCore.QRect(90, 0, 1832, 90))
        self.top_widget.setStyleSheet("QWidget{\n"
                                      "    background-color: rgb(41, 45, 57);}\n"
                                      "")
        self.top_widget.setObjectName("top_widget")
        self.page_title = QtWidgets.QLabel(self.top_widget)
        self.page_title.setGeometry(QtCore.QRect(0, 0, 1811, 90))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.page_title.setFont(font)
        self.page_title.setStyleSheet("QLabel{\n"
                                      "    color: rgb(255, 255, 255);}")
        self.page_title.setAlignment(QtCore.Qt.AlignCenter)
        self.page_title.setObjectName("page_title")
        self.notifications_button = QtWidgets.QPushButton(self.top_widget)
        self.notifications_button.setGeometry(QtCore.QRect(1450, 30, 161, 28))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.notifications_button.setFont(font)
        self.notifications_button.setStyleSheet("QPushButton{\n"
                                                "    color: rgb(255, 255, 255);}")
        self.notifications_button.setFlat(True)
        self.notifications_button.setObjectName("notifications_button")
        self.logout_button = QtWidgets.QPushButton(self.top_widget)
        self.logout_button.setGeometry(QtCore.QRect(1622, 30, 181, 28))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.logout_button.setFont(font)
        self.logout_button.setStyleSheet("QPushButton{\n"
                                         "    color: rgb(255, 255, 255);}")
        self.logout_button.setFlat(True)
        self.logout_button.setObjectName("logout_button")
        self.logout_button.clicked.connect(self.switch_to_home_page.emit)

        self.logo_frame = QtWidgets.QFrame(self.centralwidget)
        self.logo_frame.setGeometry(QtCore.QRect(0, 0, 90, 90))
        self.logo_frame.setStyleSheet("QWidget{\n"
                                      "    background-color: rgb(32, 136, 245);}")
        self.logo_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo_frame.setObjectName("logo_frame")
        self.verticale_frame = QtWidgets.QFrame(self.centralwidget)
        self.verticale_frame.setGeometry(QtCore.QRect(89, 89, 1841, 961))
        self.verticale_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verticale_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticale_frame.setObjectName("verticale_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticale_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_5 = QtWidgets.QFrame(self.verticale_frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.cosomation_frame = QtWidgets.QFrame(self.frame_5)
        self.cosomation_frame.setGeometry(QtCore.QRect(15, 15, 1031, 231))
        self.cosomation_frame.setStyleSheet("QFrame{\n"
                                            "    background-color: rgb(41, 45, 57);\n"
                                            "    border-radius:15px;}")
        self.cosomation_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cosomation_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cosomation_frame.setObjectName("cosomation_frame")
        self.consomation_title_label = QtWidgets.QLabel(self.cosomation_frame)
        self.consomation_title_label.setGeometry(QtCore.QRect(0, 140, 1031, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.consomation_title_label.setFont(font)
        self.consomation_title_label.setStyleSheet("QLabel{\n"
                                                   "    color: rgb(255, 255, 255);}")
        self.consomation_title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.consomation_title_label.setObjectName("consomation_title_label")
        self.consomation_value_label = QtWidgets.QLabel(self.cosomation_frame)
        self.consomation_value_label.setGeometry(QtCore.QRect(0, 70, 1031, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.consomation_value_label.setFont(font)
        self.consomation_value_label.setStyleSheet("QLabel{\n"
                                                   "    color: rgb(255, 255, 255);}")
        self.consomation_value_label.setAlignment(QtCore.Qt.AlignCenter)
        self.consomation_value_label.setObjectName("consomation_value_label")
        self.price_frame = QtWidgets.QFrame(self.frame_5)
        self.price_frame.setGeometry(QtCore.QRect(1055, 15, 741, 231))
        self.price_frame.setStyleSheet("QFrame{\n"
                                       "    background-color: rgb(41, 45, 57);\n"
                                       "    border-radius:15px;}")
        self.price_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.price_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.price_frame.setObjectName("price_frame")
        self.price_value_label = QtWidgets.QLabel(self.price_frame)
        self.price_value_label.setGeometry(QtCore.QRect(0, 70, 741, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.price_value_label.setFont(font)
        self.price_value_label.setStyleSheet("QLabel{\n"
                                             "    color: rgb(255, 255, 255);}")
        self.price_value_label.setAlignment(QtCore.Qt.AlignCenter)
        self.price_value_label.setObjectName("price_value_label")
        self.price_title_label = QtWidgets.QLabel(self.price_frame)
        self.price_title_label.setGeometry(QtCore.QRect(4, 140, 741, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.price_title_label.setFont(font)
        self.price_title_label.setStyleSheet("QLabel{\n"
                                             "    color: rgb(255, 255, 255);}")
        self.price_title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.price_title_label.setObjectName("price_title_label")
        self.show_statistics()
        self.verticalLayout.addWidget(self.frame_5)
        self.menu_frame = QtWidgets.QFrame(self.centralwidget)
        self.menu_frame.setGeometry(QtCore.QRect(0, 90, 90, 961))
        self.menu_frame.setStyleSheet("QWidget{\n"
                                      "    background-color: rgb(41, 45, 57);}\n"
                                      "")
        self.menu_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_frame.setObjectName("menu_frame")
        self.dashboard_icon_button = QtWidgets.QPushButton(self.menu_frame)
        self.dashboard_icon_button.setGeometry(QtCore.QRect(0, 200, 90, 79))
        self.dashboard_icon_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/dashbord.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dashboard_icon_button.setIcon(icon)
        self.dashboard_icon_button.setIconSize(QtCore.QSize(70, 70))
        self.dashboard_icon_button.setFlat(True)
        self.dashboard_icon_button.setObjectName("dashboard_icon_button")
        self.dashboard_icon_button.clicked.connect(self.switch_to_dashboard_page.emit)

        self.dashboard_button1 = QtWidgets.QPushButton(self.menu_frame)
        self.dashboard_button1.setGeometry(QtCore.QRect(0, 280, 90, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.dashboard_button1.setFont(font)
        self.dashboard_button1.setStyleSheet("QPushButton{\n"
                                             "    color: rgb(255, 255, 255);}")
        self.dashboard_button1.setFlat(True)
        self.dashboard_button1.setObjectName("dashboard_button1")
        self.dashboard_button1.clicked.connect(self.switch_to_dashboard_page.emit)

        self.dashboard_button2 = QtWidgets.QPushButton(self.menu_frame)
        self.dashboard_button2.setGeometry(QtCore.QRect(0, 300, 90, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.dashboard_button2.setFont(font)
        self.dashboard_button2.setStyleSheet("QPushButton{\n"
                                             "    color: rgb(255, 255, 255);}")
        self.dashboard_button2.setFlat(True)
        self.dashboard_button2.setObjectName("dashboard_button2")
        self.dashboard_button2.clicked.connect(self.switch_to_dashboard_page.emit)

        self.consomation_icon_button = QtWidgets.QPushButton(self.menu_frame)
        self.consomation_icon_button.setGeometry(QtCore.QRect(0, 360, 90, 79))
        self.consomation_icon_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icons/Compteur-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.consomation_icon_button.setIcon(icon1)
        self.consomation_icon_button.setIconSize(QtCore.QSize(70, 70))
        self.consomation_icon_button.setFlat(True)
        self.consomation_icon_button.setObjectName("consomation_icon_button")
        self.consomation_icon_button.clicked.connect(self.switch_to_consumption_page.emit)

        self.consomation_button = QtWidgets.QPushButton(self.menu_frame)
        self.consomation_button.setGeometry(QtCore.QRect(0, 440, 90, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.consomation_button.setFont(font)
        self.consomation_button.setStyleSheet("QPushButton{\n"
                                              "    color: rgb(255, 255, 255);}")
        self.consomation_button.setFlat(True)
        self.consomation_button.setObjectName("consomation_button")
        self.consomation_button.clicked.connect(self.switch_to_consumption_page.emit)

        self.onduleur_icon_button = QtWidgets.QPushButton(self.menu_frame)
        self.onduleur_icon_button.setGeometry(QtCore.QRect(0, 500, 90, 79))
        self.onduleur_icon_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../icons/onduleur-icon1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.onduleur_icon_button.setIcon(icon2)
        self.onduleur_icon_button.setIconSize(QtCore.QSize(70, 70))
        self.onduleur_icon_button.setFlat(True)
        self.onduleur_icon_button.setObjectName("onduleur_icon_button")
        self.onduleur_icon_button.clicked.connect(self.switch_to_onduleurs_page.emit)

        self.onduleur_button = QtWidgets.QPushButton(self.menu_frame)
        self.onduleur_button.setGeometry(QtCore.QRect(0, 580, 90, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.onduleur_button.setFont(font)
        self.onduleur_button.setStyleSheet("QPushButton{\n"
                                           "    color: rgb(255, 255, 255);}")
        self.onduleur_button.setFlat(True)
        self.onduleur_button.setObjectName("onduleur_button")
        self.onduleur_button.clicked.connect(self.switch_to_onduleurs_page.emit)

        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

        self.layout.addWidget(self.centralwidget)
        self.layout.setContentsMargins(0, 0, 0, 0)
        self.setLayout(self.layout)


    def show_statistics(self):
        self.statistics_stackedWidget = QtWidgets.QStackedWidget(self.frame_5)
        self.statistics_stackedWidget.setGeometry(QtCore.QRect(15, 260, 1781, 671))
        self.statistics_stackedWidget.setObjectName("stackedWidget")
        self.week_statistics_page = QtWidgets.QWidget()
        self.week_statistics_page.setObjectName("six_months_statistiques")
        self.week_frame = QtWidgets.QFrame(self.week_statistics_page)
        self.week_frame.setGeometry(QtCore.QRect(0, 0, 1781, 671))
        self.week_frame.setStyleSheet("QFrame{\n"
                                      "    background-color: rgb(41, 45, 57);\n"
                                      "    border-radius:15px;}")
        self.week_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.week_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.week_frame.setObjectName("six_monthe_frame")
        self.week_frame_title = QtWidgets.QLabel(self.week_frame)
        self.week_frame_title.setGeometry(QtCore.QRect(10, 0, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.week_frame_title.setFont(font)
        self.week_frame_title.setStyleSheet("QLabel{\n"
                                            "    color: rgb(255, 255, 255);}")
        self.week_frame_title.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.week_frame_title.setObjectName("six_month_frame_title")
        self.week_label = QtWidgets.QLabel(self.week_frame)
        self.week_label.setGeometry(QtCore.QRect(841, 1, 138, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.week_label.setFont(font)
        self.week_label.setStyleSheet("QLabel{\n"
                                      "    color: rgb(255, 255, 255);}")
        self.week_label.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.week_label.setObjectName("six_month_label")
        self.week_plots_widget = QWidget(self.week_frame)
        self.week_plots_widget.setGeometry(QtCore.QRect(40, 70, 1710, 580))
        self.week_plots_widget.setStyleSheet("background-color: rgb(255, 255, 255);")

        self.week_plots = WeekPlots(parent=self.week_plots_widget)
        self.week_plots.setGeometry(QtCore.QRect(0, 0, 1710, 580))
        self.next_button_1 = QtWidgets.QPushButton(self.week_frame)
        self.next_button_1.setGeometry(QtCore.QRect(994, 9, 33, 29))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../Downloads/next-svgrepo-com.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.next_button_1.setIcon(icon1)
        self.next_button_1.setFlat(True)
        self.next_button_1.setObjectName("next_button")
        self.next_button_1.clicked.connect(self.next)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Downloads/next-svgrepo-com (1).png"), QtGui.QIcon.Normal,
                       QtGui.QIcon.Off)

        self.statistics_stackedWidget.addWidget(self.week_statistics_page)

        self.month_statistiques_page = QtWidgets.QWidget()
        self.month_statistiques_page.setObjectName("month_statistiques_page")
        self.month_frame = QtWidgets.QFrame(self.month_statistiques_page)
        self.month_frame.setGeometry(QtCore.QRect(0, 0, 1781, 671))
        self.month_frame.setStyleSheet("QFrame{\n"
                                       "    background-color: rgb(41, 45, 57);\n"
                                       "    border-radius:15px;}")
        self.month_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.month_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.month_frame.setObjectName("month_frame")
        self.month_frame_title = QtWidgets.QLabel(self.month_frame)
        self.month_frame_title.setGeometry(QtCore.QRect(10, 0, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.month_frame_title.setFont(font)
        self.month_frame_title.setStyleSheet("QLabel{\n"
                                             "    color: rgb(255, 255, 255);}")
        self.month_frame_title.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.month_frame_title.setObjectName("month_frame_title")
        self.nextButton_2 = QtWidgets.QPushButton(self.month_frame)
        self.nextButton_2.setGeometry(QtCore.QRect(978, 9, 33, 29))
        self.nextButton_2.setText("")
        self.nextButton_2.setIcon(icon1)
        self.nextButton_2.setFlat(True)
        self.nextButton_2.setObjectName("pushButton_9")
        self.nextButton_2.clicked.connect(self.next)
        self.backButton_2 = QtWidgets.QPushButton(self.month_frame)
        self.backButton_2.setGeometry(QtCore.QRect(792, 9, 33, 29))
        self.backButton_2.setText("")
        self.backButton_2.setIcon(icon)
        self.backButton_2.setFlat(True)
        self.backButton_2.setObjectName("pushButton_10")
        self.backButton_2.clicked.connect(self.back)
        self.month_label = QtWidgets.QLabel(self.month_frame)
        self.month_label.setGeometry(QtCore.QRect(850, 0, 101, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.month_label.setFont(font)
        self.month_label.setStyleSheet("QLabel{\n"
                                        "    color: rgb(255, 255, 255);}")
        self.month_label.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.month_label.setObjectName("week_label_5")
        self.month_plots_widget = QWidget(self.month_frame)
        self.month_plots_widget.setGeometry(QtCore.QRect(40, 70, 1710, 580))
        self.month_plots_widget.setStyleSheet("background-color: rgb(255, 255, 255);")

        self.month_plots = MonthPlots(parent=self.month_plots_widget)
        self.month_plots.setGeometry(QtCore.QRect(0, 0, 1710, 580))
        self.statistics_stackedWidget.addWidget(self.month_statistiques_page)
        self.six_months_statistiques = QtWidgets.QWidget()
        self.six_months_statistiques.setObjectName("six_months_statistiques")
        self.six_monthe_frame = QtWidgets.QFrame(self.six_months_statistiques)
        self.six_monthe_frame.setGeometry(QtCore.QRect(0, 0, 1781, 671))
        self.six_monthe_frame.setStyleSheet("QFrame{\n"
                                            "    background-color: rgb(41, 45, 57);\n"
                                            "    border-radius:15px;}")
        self.six_monthe_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.six_monthe_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.six_monthe_frame.setObjectName("six_monthe_frame")
        self.six_month_frame_title = QtWidgets.QLabel(self.six_monthe_frame)
        self.six_month_frame_title.setGeometry(QtCore.QRect(10, 0, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.six_month_frame_title.setFont(font)
        self.six_month_frame_title.setStyleSheet("QLabel{\n"
                                                 "    color: rgb(255, 255, 255);}")
        self.six_month_frame_title.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.six_month_frame_title.setObjectName("six_month_frame_title")
        self.six_month_label = QtWidgets.QLabel(self.six_monthe_frame)
        self.six_month_label.setGeometry(QtCore.QRect(841, 1, 138, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.six_month_label.setFont(font)
        self.six_month_label.setStyleSheet("QLabel{\n"
                                           "    color: rgb(255, 255, 255);}")
        self.six_month_label.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.six_month_label.setObjectName("six_month_label")
        self.six_month_plots_widget = QWidget(self.six_monthe_frame)
        self.six_month_plots_widget.setGeometry(QtCore.QRect(40, 70, 1710, 580))
        self.six_month_plots_widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.six_month_plots = SixMonthPlots(parent=self.six_month_plots_widget)
        self.six_month_plots.setGeometry(QtCore.QRect(0, 0, 1710, 580))

        self.backButton_3 = QtWidgets.QPushButton(self.six_monthe_frame)
        self.backButton_3.setGeometry(QtCore.QRect(793, 9, 33, 29))
        self.backButton_3.setText("")
        self.backButton_3.setIcon(icon)
        self.backButton_3.setFlat(True)
        self.backButton_3.setObjectName("pushButton_12")
        self.backButton_3.clicked.connect(self.back)
        self.statistics_stackedWidget.addWidget(self.six_months_statistiques)
        self.week_label.setText("Semaine")
        self.month_label.setText("1-Mois")
        self.six_month_label.setText("6-Mois")
        self.statistics_stackedWidget.setCurrentIndex(0)


    def next(self):
        self.counter += 1
        self.statistics_stackedWidget.setCurrentIndex(self.counter)



    def back(self):
        self.counter -= 1
        self.statistics_stackedWidget.setCurrentIndex(self.counter)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.page_title.setText(_translate("MainWindow", "Statistiques"))
        self.notifications_button.setText(_translate("MainWindow", "Notifications"))
        self.logout_button.setText(_translate("MainWindow", "Deconnecter"))
        self.consomation_title_label.setText(_translate("MainWindow", "Consomation actuel"))
        self.consomation_value_label.setText(_translate("MainWindow", "11111111111 kW"))
        self.price_value_label.setText(_translate("MainWindow", "11111111111 DH"))
        self.price_title_label.setText(_translate("MainWindow", "Cout"))
        self.week_frame_title.setText(_translate("MainWindow", "Statistiques :"))
        self.month_frame_title.setText(_translate("MainWindow", "Statistiques :"))
        self.six_month_frame_title.setText(_translate("MainWindow", "Statistiques :"))
        self.dashboard_button1.setText(_translate("MainWindow", "Tableau"))
        self.dashboard_button2.setText(_translate("MainWindow", "de bord"))
        self.consomation_button.setText(_translate("MainWindow", "Consomation"))
        self.onduleur_button.setText(_translate("MainWindow", "Onduleurs"))



